### ISSUE TITLE
Document User Epic for Monitoring and Alerting

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#102]
From discussion on 3/3/2021

**Comment by 4n4nd** [comment]
The current suggestion is to:
* Use Openshift User Workload Monitoring to monitor metrics and set up alerts
* Use the Observatorium Operator that comes with ACM to set up Thanos for long term metric storage as well as deploy Loki for logs collection

**Comment by tumido** [comment]
cc @4n4nd


linking related issues: https://github.com/operate-first/apps/issues/193, https://github.com/operate-first/SRE/issues/56

**Comment by HumairAK** [comment]
stale issue, we're using UWM and observatorium -> thanos for longterm storage, closing.
