### ISSUE TITLE
[Migration to 4.7] Create a series of post-install steps that will need to take place to restore cluster state of the moc-cnv cluster.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#104]
Result should be a new issue, with a list of checkboxes. This list of steps should serve as a guidance for the series of actions we will need to take in order to restore all argocd apps, deployments, operators, namespaces, etc.

**Comment by HumairAK** [comment]
Let's also include the list of pre-install steps / measures we will be taking as well.

**Comment by HumairAK** [comment]
@durandom suggested doing a live stream (on youtube?) for full transparency.

**Comment by durandom** [comment]
@oindrillac can you have a look at the [Google Meet](https://support.google.com/meet/answer/9308630?co=GENIE.Platform%3DDesktop&hl=en&authuser=1&oco=0) documentation to see how we could stream and record the upgrade in a meeting? 
Then post the recording on our YT channel.

**Comment by HumairAK** [comment]
I've created the series of steps [here](https://github.com/operate-first/SRE/issues/108), reserve discussions about the steps here (i.e. if anything should be added/etc.), and edit the issue directoy. Let's save the comments space for the day of migration.

**Comment by HumairAK** [comment]
Issue was resolved.
