### ISSUE TITLE
Migration to 4.7 new "zero" cluster

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#108]
Pre-Install steps: 
- [x] Create PR for upgrading operator subscriptions to 4.7: [done](https://github.com/operate-first/apps/pull/288)
- [x] Update directory structures to reflect new name as decided [here](https://github.com/open-infrastructure-labs/ops-issues/issues/34)
  - Update directories in apps repo
  - Update direcotires in argocd-apps repo (as well as the destionation paths for the apps that point to old cnv name)

Post - Install steps: 

Pre-Condition: The new CNV cluster has been redeployed via ACM as per [this task](https://github.com/open-infrastructure-labs/ops-issues/issues/34).

- [x] Update Operator subscriptions to 4.7 (https://github.com/operate-first/apps/pull/288)
- [x] Update ArgoCD CNV cluster spec (https://github.com/operate-first/continuous-deployment/pull/126)
- [x] Ensure all apps in argocd-apps for cnv point to the new cluster name (https://github.com/operate-first/argocd-apps/pull/92)
- [x] Ensure all ArgoCD Projects have the permissions to deploy to this new clusters (https://github.com/operate-first/continuous-deployment/pull/124)
- [x] Turn of auto-sync for app-of-apps (https://github.com/operate-first/continuous-deployment/pull/125)
- [x] Deploy ArgoCD 
- [x] Deploy cluster resources, ensure all namespaces/groups/operators etc. are deployed successfully. 
- [x] Deploy operate-first apps 
- [x] Deploy all other argocd project applications
- [x] Re-enable github alerts (https://github.com/operate-first/SRE/issues/111) (https://github.com/operate-first/apps/pull/315)
- [x] Update documentation with new routes (e.g. [the routes here](https://github.com/search?q=org%3Aoperate-first+apps.cnv.massopen.cloud&type=code))
    - [x] https://github.com/operate-first/SRE/pull/114
    - [x] https://github.com/operate-first/support/pull/112
    - [x] https://github.com/operate-first/apps/pull/314

**Comment by 4n4nd** [comment]
let's add a step to re-enable alerts after the reinstall is complete (related https://github.com/operate-first/SRE/issues/111)

**Comment by HumairAK** [comment]
Kubeflow Kfdef also needed to be manually sync'd first before we could sync the profile

**Comment by HumairAK** [comment]
Kafka was not deployed (even though the kfdef was)

**Comment by HumairAK** [comment]
```
time="2021-03-09T21:00:29Z" level=info msg="Reconciling KfDef resources. Request.Namespace: opf-superset, Request.Name: opendatahub."
time="2021-03-09T21:00:29Z" level=info msg="Creating a new KubeFlow Deployment. KubeFlow.Namespace: opf-superset."
time="2021-03-09T21:00:29Z" level=info msg="Creating directory /tmp/opf-superset/opendatahub/.cache"
time="2021-03-09T21:00:29Z" level=info msg="Fetching https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.2 to /tmp/opf-superset/opendatahub/.cache/manifests"
time="2021-03-09T21:00:29Z" level=info msg="Updating localPath to /tmp/opf-superset/opendatahub/.cache/manifests/opendatahub-io-odh-manifests-d680c04"
time="2021-03-09T21:00:29Z" level=info msg="Fetch succeeded; LocalPath /tmp/opf-superset/opendatahub/.cache/manifests/opendatahub-io-odh-manifests-d680c04"
time="2021-03-09T21:00:29Z" level=info msg="Fetching https://github.com/operate-first/apps/tarball/master to /tmp/opf-superset/opendatahub/.cache/opf"
time="2021-03-09T21:00:29Z" level=info msg="Updating localPath to /tmp/opf-superset/opendatahub/.cache/opf/operate-first-apps-1f42e09"
time="2021-03-09T21:00:29Z" level=info msg="Fetch succeeded; LocalPath /tmp/opf-superset/opendatahub/.cache/opf/operate-first-apps-1f42e09"
time="2021-03-09T21:00:29Z" level=info msg="Processing application: odh-common"
time="2021-03-09T21:00:29Z" level=info msg="Processing application: superset"
time="2021-03-09T21:00:29Z" level=info msg="Processing application: superset"
time="2021-03-09T21:00:29Z" level=error msg="failed to build kfApp from URI /tmp/opf-superset/opendatahub/config.yaml: Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: Kustomize generate failed:  (kubeflow.error): Code 500 with message: couldn't copy application superset: lstat /tmp/opf-superset/opendatahub/.cache/opf/operate-first-apps-1f42e09/odh/overlays/moc/superset/overrides: no such file or directory."
time="2021-03-09T21:00:29Z" level=error msg="Failed to load KfApp. Error: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: Kustomize generate failed:  (kubeflow.error): Code 500 with message: couldn't copy application superset: lstat /tmp/opf-superset/opendatahub/.cache/opf/operate-first-apps-1f42e09/odh/overlays/moc/superset/overrides: no such file or directory."

```

**Comment by HumairAK** [comment]
Superset, Strimzi & Kafka deployed

**Comment by HumairAK** [comment]
I think we can call the migration of all apps/services complete, if I've missed anything feel free to re-open!
