### ISSUE TITLE
Define Machine Health Checks for Baremetal install - MOC Infra

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#112]
We're missing `MachineHealthChecks` for MOC Infra and possibly Zero cluster. We should have a complete understanding of node stability:
https://console-openshift-console.apps.moc-infra.massopen.cloud/k8s/ns/openshift-machine-api/machine.openshift.io~v1beta1~MachineHealthCheck

https://docs.openshift.com/container-platform/4.6/machine_management/deploying-machine-health-checks.html#machine-health-checks-bare-metal_deploying-machine-health-checks

**Comment by larsks** [comment]
The docs have this interesting note:

> - Only machines owned by a machine set are remediated by a machine health check.

Since the nodes added post-install aren't part of a machineset, this looks like more than just a minor workflow change. I already have https://access.redhat.com/support/cases/#/case/02888583 open on the question of managing bare metal nodes in 4.7.

**Comment by tumido** [comment]
we can define health checks for worker nodes. Let's start with that.
