### ISSUE TITLE
MOC Infra cluster - find a remendiation for SystemMemoryExceedsReservation warning

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#113]
MOC Infra reports `SystemMemoryExceedsReservation` alert for `os-ctrl-2` node:
https://console-openshift-console.apps.moc-infra.massopen.cloud/monitoring/alerts/1150787716?alertname=SystemMemoryExceedsReservation&node=os-ctrl-2&severity=warning
![image](https://user-images.githubusercontent.com/7453394/110140094-04ae4280-7dd4-11eb-9794-15e58232a8da.png)

The `os-ctrl-2` node is not in Memory pressure.

```
oc describe nodes/os-ctrl-2
...
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Fri, 05 Mar 2021 16:58:18 +0100   Thu, 18 Feb 2021 13:52:27 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Fri, 05 Mar 2021 16:58:18 +0100   Thu, 18 Feb 2021 13:52:27 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Fri, 05 Mar 2021 16:58:18 +0100   Thu, 18 Feb 2021 13:52:27 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Fri, 05 Mar 2021 16:58:18 +0100   Thu, 18 Feb 2021 13:56:18 +0100   KubeletReady                 kubelet is posting ready status
```

Currently there's no official remediation:
https://access.redhat.com/solutions/5788171

**Comment by larsks** [comment]
> MOC Infra cluster is small

These systems each have 264 GB of RAM. That's approaching 1TB of memory for the cluster. There aren't a lot of machines, but I'd be hard pressed to describe this as "small". Is this just an inappropriately sized reservation somewhere?

**Comment by ipolonsk** [comment]
We have two other BM servers that were part of the cnv2 cluster (one of them had a hardware booting issue, not sure what is the status of that now). @larsks maybe we can add those two servers to moc-infra cluster?

**Comment by HumairAK** [comment]
I see this alert firing for `os-ctrl-1` as well sicne march 9: 

![image](https://user-images.githubusercontent.com/10904967/110829947-a9160600-8266-11eb-8799-3ae1e40a5585.png)

**Comment by tumido** [comment]
Duplicate of autocreated: https://github.com/operate-first/SRE/issues/146
