### ISSUE TITLE
MOC Zero cluster CLO Job alert

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#123]
KubeJobFailed

Job openshift-logging/elasticsearch-im-audit-1615392900 failed to complete. Removing failed job after investigation should clear this alert.

https://console-openshift-console.apps.zero.massopen.cloud/monitoring/alerts/1992863371?alertname=KubeJobFailed&condition=true&container=kube-rbac-proxy-main&endpoint=https-main&instance=10.131.0.17%3A8443&job=kube-state-metrics&job_name=elasticsearch-im-audit-1615392900&namespace=openshift-logging&pod=kube-state-metrics-749954d685-k8btj&service=kube-state-metrics&severity=warning

logs:
```
{"error":{"root_cause":[{"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"}],"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"},"status":500}
Error while attemping to determine the active write alias: {"error":{"root_cause":[{"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"}],"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"},"status":500}
{"error":{"root_cause":[{"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"}],"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"},"status":500}
Error while attemping to determine the active write alias: {"error":{"root_cause":[{"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"}],"type":"security_exception","reason":"Unexpected exception indices:admin/aliases/get"},"status":500}
```

This points to:
https://bugzilla.redhat.com/show_bug.cgi?id=1900873
https://bugzilla.redhat.com/show_bug.cgi?id=1866019
https://bugzilla.redhat.com/show_bug.cgi?id=1890838

We experienced the same on CNV before, we may need to investigate further.

**Comment by HumairAK** [comment]
It seems like the jobs ended up running again and complete successfully later: 

```
$ oc get pods | grep -E 'STATUS|elasticsearch-im*'
NAME                                            READY     STATUS      RESTARTS   AGE
elasticsearch-im-app-1615409100-6qkx9           0/1       Completed   0          12m
elasticsearch-im-audit-1615404600-74sxj         0/1       Error       0          87m
elasticsearch-im-audit-1615409100-d2sc4         0/1       Completed   0          12m
elasticsearch-im-infra-1615396500-zjzx9         0/1       Error       0          3h42m
elasticsearch-im-infra-1615409100-lt7b7         0/1       Completed   0          12m
```

But yeah as said earlier, this is a similar pattern we witnessed in the old cnv cluster.

**Comment by tumido** [comment]
Related:
https://github.com/operate-first/SRE/issues/149
https://github.com/operate-first/SRE/issues/154
