### ISSUE TITLE
MOC Zero - Cluster operators degraded

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#126]
@HumairAK  noticed couple of alerts on the Zero cluster (originally just `version`, now multiple cluster operators)

https://console-openshift-console.apps.zero.massopen.cloud/monitoring/alerts?rowFilter-alert-state=firing&rowFilter-alert-source=platform&orderBy=asc&sortBy=Name

https://console-openshift-console.apps.zero.massopen.cloud/settings/cluster/clusteroperators?rowFilter-cluster-operator-status=Degraded
![image](https://user-images.githubusercontent.com/7453394/110810170-d0c89680-8285-11eb-99c0-d373903f458e.png)

**Comment by HumairAK** [comment]
We also noticed that volume metrics were not being picked up for certain PVC's, I'm suspecting the monitoring degradation may be the cause. @4n4nd

**Comment by tumido** [comment]
`os-wrk-2` is reporting Not Ready

```
$ oc get nodes
NAME        STATUS     ROLES    AGE   VERSION
os-ctrl-0   Ready      master   2d    v1.20.0+ba45583
os-ctrl-1   Ready      master   2d    v1.20.0+ba45583
os-ctrl-2   Ready      master   2d    v1.20.0+ba45583
os-sto-0    Ready      worker   2d    v1.20.0+ba45583
os-sto-1    Ready      worker   2d    v1.20.0+ba45583
os-sto-2    Ready      worker   2d    v1.20.0+ba45583
os-wrk-0    Ready      worker   2d    v1.20.0+ba45583
os-wrk-1    Ready      worker   41h   v1.20.0+ba45583
os-wrk-2    NotReady   worker   16h   v1.20.0+ba45583
```

**Comment by larsks** [comment]
@tumido still pursuing https://access.redhat.com/support/cases/#/case/02888583. os-wrk-[1,2] will continue to be up and down until the questions in that issue are resolved.

**Comment by tumido** [comment]
I think the alerts are firing because of the nodes not being available (cluster operators usually run on all nodes). So that might be the source. :+1:

**Comment by tumido** [comment]
These alerts are no longer firing, closing
