### ISSUE TITLE
Define burn-rate based alerts for Jupyterhub SLOs

### ISSUE THREAD

**Issue by anishasthana** [operate-first/SRE#129]
Once we have defined SLOs for Jupyterhub in #128 , we should create burn-rate based alerts for the SLOs we agreed on.

**Comment by anishasthana** [comment]
I think an easy way to go about it. ++

**Comment by hemajv** [comment]
I like that idea :+1:

**Comment by HumairAK** [comment]
Related: https://github.com/operate-first/SRE/issues/247

**Comment by anishasthana** [comment]
@HumairAK should we close this issue out in favour of the new one I created?

**Comment by HumairAK** [comment]
yep
