### ISSUE TITLE
Add documentation for monitoring setup

### ISSUE THREAD

**Issue by hemajv** [operate-first/SRE#13]
Add documentation/best practices on setting up an open/public monitoring stack
Follows #11

**Comment by HumairAK** [comment]
Hrmm this is old and I can't remember the motivation behind this, but we have described our monitoring stack/setup in this adr here: https://github.com/operate-first/blueprint/blob/main/docs/adr/0006-monitoring-structure.md

And links to the services/dashboards are found on the support [readme](https://github.com/operate-first/support) as well as [documentation](https://github.com/operate-first/apps/tree/master/docs/odh) for enabling applications to be monitored by the stack. I'm gonna guess that should be sufficient. Feel free to re-open if there's more.
