### ISSUE TITLE
Enable Monitoring for ODH operator

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#131]
Noticed there is a service: `opendatahub-operator-metrics` in `openhisft-operators` namespace, that exposes some ODH metrics, let's get this in prometheus via service monitor.

**Comment by anishasthana** [comment]
@HumairAK  Upstream already has monitoring for ODH https://github.com/opendatahub-io/odh-manifests/blob/master/prometheus/operator/base/servicemonitor.yaml#L9

**Comment by 4n4nd** [comment]
Related PR: https://github.com/operate-first/apps/pull/378#issuecomment-799464471

**Comment by anishasthana** [comment]
I opened https://github.com/opendatahub-io/odh-manifests/pull/349 to update the upstream scrape configs

**Comment by anishasthana** [comment]
Argo metrics scraping should be fixed now as well: https://github.com/operate-first/apps/pull/385

**Comment by anishasthana** [comment]
ODH Operator metrics are available now: http://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph?g0.range_input=1h&g0.expr=%7Bjob%3D%22opendatahub-operator-metrics%22%7D&g0.tab=1
