### ISSUE TITLE
Create a predict_linear alert on the Thanos PVC

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#132]
@4n4nd should we create a `[predict_linear](https://prometheus.io/docs/prometheus/latest/querying/functions/#predict_linear)` alert on the Thanos PVC? We could even set it up for other key PVCs, now that I think of it.

_Originally posted by @anishasthana in https://github.com/operate-first/apps/issues/379#issuecomment-799464902_

**Comment by 4n4nd** [comment]
@hemajv is our sme on alerting stuff, wdyt?

**Comment by anishasthana** [comment]
I think we can also set it up more broadly. Things like the jupyterhub DB PVC, for example.

**Comment by hemajv** [comment]
> @hemajv is our sme on alerting stuff, wdyt?

Yes, I think it'll be a good use case to test out `predict_linear` and observe the predictions. And if they seem good, we can extend it to others.
