### ISSUE TITLE
Alerting, SLIs/SLOs for Kafka

### ISSUE THREAD

**Issue by hemajv** [operate-first/SRE#133]
Now that we have metrics available for Kafka, we should define SLI/SLOs and set up alerting for it.

cc @anishasthana @accorvin @maulikjs

**Comment by anishasthana** [comment]
I pointed @hemajv at some internal docs/dashboards to get started :-)

**Comment by goern** [comment]
@hemajv is this only for kafka itself, or also for topic maintained by op1st? could a requestor (or declarator) of a topic also add SLI/SLO/Altert?

@kpostoffice @pacospace

**Comment by anishasthana** [comment]
The focus here is on Kafka health. Some our SLIs/SLOs can be around health of topics -- things like under-replicated or offline partitions. With how Alerting rules work with the prometheus operator, it is very easy for end-users of the topics to define their own alerts and routing.

**Comment by hemajv** [comment]
Related: #247
