### ISSUE TITLE
Define and Document process for end-user alerting

### ISSUE THREAD

**Issue by anishasthana** [operate-first/SRE#135]
Prompted by #133 

We should define a process for operate-first users to follow such that they can set up alerting with Prometheus metrics. Things to cover (off the top of my head) are

1) Alerting rules and where to store them such that Prometheus can discover them
2) Alert Routing
3) Alert "destinations". I believe we currently only support the Github Alerts receiver, so we should have a well documented process to follow for end-users so that they can host their own.
4) Ideally, we'd figure out how to get email alerts working as well -- this would require an SMTP server on the MOC.

**Comment by tumido** [comment]
:+1: For MOC may be able to use MOC mailing server instead of deploying our own SMTP.
