### ISSUE TITLE
Latest metrics for Jupyterhub

### ISSUE THREAD

**Issue by hemajv** [operate-first/SRE#16]
There seems to be new monitoring metrics supported for Jupyterhub such as: https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/metrics.py#L38

Some of these new metrics would be useful in monitoring our jupyterhub service such as:
- `RUNNING_SERVERS` - the number of user servers currently running
- `TOTAL_USERS` - total number of users
- `HUB_STARTUP_DURATION_SECONDS` - time taken for hub to start

However, this is supported in the newest Jupyterhub version (1.2.1) whereas the current ODH Jupyterhub version seems to be behind ([0.9.4](https://github.com/opendatahub-io/jupyterhub-quickstart/blob/3.0.7/requirements.txt#L1))

cc @anishasthana @HumairAK

**Comment by HumairAK** [comment]
Agreed these metrics sounds incredibly useful, let's get an issue upstream about this to update JH so we can take advantage of these metrics as well, great job @hemajv  !

**Comment by hemajv** [comment]
Looks like this will be available in the ODH 0.9.1 release (as per Vasek)

**Comment by hemajv** [comment]
We now have these metrics available with the recent `ODH 1.0.0` upgrade :tada:

Metrics: http://prometheus-portal-opf-monitoring.apps.cnv.massopen.cloud/graph?g0.range_input=1h&g0.expr=jupyterhub_running_servers&g0.tab=1&g1.range_input=1h&g1.expr=jupyterhub_total_users&g1.tab=1&g2.range_input=1h&g2.expr=jupyterhub_hub_startup_duration_seconds_count&g2.tab=1
