### ISSUE TITLE
Prototype: Have alerts integrated with github

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#19]
Based on the spike #14

**Comment by hemajv** [comment]
This would require:

1. Deploying Prometheus
2. Configuring Alertmanager with Prometheus
3. Adding alerting rules
4. Adding Github alertmanager as a receiver

**Comment by hemajv** [comment]
Tested Prometheus and Alertmanager with the following configs: https://github.com/hemajv/odh/tree/add-monitoring/kfdef/monitoring

**Comment by hemajv** [comment]
When configuring the Alertmanager, we ran into the following issue: https://github.com/operate-first/odh/issues/30

**Comment by hemajv** [comment]
Deployed the Github alertmanager receiver locally and created a test alert: https://github.com/hemajv/test/issues/1

**Comment by HumairAK** [comment]
@durandom

**Comment by hemajv** [comment]
Created an issue: https://github.com/m-lab/alertmanager-github-receiver/issues/49
for additional documentation on how to deploy the GitHub alertmanager receiver and configure Prometheus alerts

**Comment by hemajv** [comment]
Based on the provided documentation, we were able to deploy the GitHub alertmanager receiver in quicklab and route our Prometheus alerts to it. 

Test alert was created here: https://github.com/hemajv/test/issues/3

**Comment by hemajv** [comment]
@HumairAK @4n4nd which repo would be the best place to include all the GitHub alertmanager configuration files and documentation?

**Comment by HumairAK** [comment]
If it's general configurations then [here](https://github.com/operate-first/odh/tree/master/base/monitoring), by general I mean we can include this in quicklab/crc/other environments. If it's moc specific, then add it directly in the overlay [here](https://github.com/operate-first/odh/tree/master/overlays/moc/monitoring). 

For docs, I'm not sure which repo. I'm thinking if it's operational related, i.e. how to configure it (ops related) then it should go in the `odh` repo, if it's to inform sre practices (links, sli's we alert on, etc.) then in this repo. Open to suggestions.

**Comment by 4n4nd** [comment]
let's keep the deployment resources in the [odh](https://github.com/operate-first/odh/tree/master/base/monitoring) repo and all the other configuration stuff in here (SRE repo). We could just add the links to these configs in the MOC overlay in the odh repo.

**Comment by HumairAK** [comment]
I'm fine with this, we can also pull in configurations via kustomize remote links if the cr's themselves don't have a direct link option like the dashboard resource.

**Comment by 4n4nd** [comment]
> I'm fine with this, we can also pull in configurations via kustomize remote links if the cr's themselves don't have a direct link option like the dashboard resource.

yep that's what i meant

**Comment by hemajv** [comment]
okay cool, sounds good to me :+1:
