### ISSUE TITLE
Incident: Storage Error

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#224]
Alert: https://github.com/operate-first/alerts/issues/213
![image](https://user-images.githubusercontent.com/7453394/111809096-e87ecb00-88d4-11eb-913e-97360346e261.png)
![image](https://user-images.githubusercontent.com/7453394/111809125-f0d70600-88d4-11eb-9c0e-87c6585981f4.png)

https://console-openshift-console.apps.zero.massopen.cloud/monitoring/alerts/3247418476?alertname=CephClusterErrorState&container=mgr&endpoint=http-metrics&instance=10.129.6.141%3A9283&job=rook-ceph-mgr&namespace=openshift-storage&pod=rook-ceph-mgr-a-86df6c5fc-57sfd&service=rook-ceph-mgr&severity=critical

/cc @HumairAK @4n4nd @larsks

**Comment by tumido** [comment]
https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/openshift-storage/pods/rook-ceph-osd-prepare-ocs-deviceset-1-data-0-b4cfv-dzgjx/events

Couple of pods are stuck in pending state, reporting:
```
0/9 nodes are available: 9 persistentvolumeclaim "ocs-deviceset-1-data-0-b4cfv" not found.
```

**Comment by larsks** [comment]
Well, that's exciting. Taking a look.

**Comment by tumido** [comment]
Node down:
https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/nodes/os-wrk-1

reporting: Scheduling disabled, missing Machine resource

**Comment by larsks** [comment]
The node down is  a red herring; I've had the marked as `SchedulingDisabled` for a while. It needs to be re-provisioned, but I've been holding off while looking at the storage issues.

**Comment by larsks** [comment]
Ceph was reporting:

```
sh-4.4# ceph status
  cluster:
    id:     895c1f68-fc4c-4355-a7bf-51c57c78d59b
    health: HEALTH_ERR
            1 scrub errors
            Possible data damage: 1 pg inconsistent
```

Running `ceph pg repair` on the affected pg seems to have returned the
cluster to `HEALTH_OK`.

```
sh-4.4# ceph status
  cluster:
    id:     895c1f68-fc4c-4355-a7bf-51c57c78d59b
    health: HEALTH_OK
```

I'm currently investigating what devices were
involved.

**Comment by larsks** [comment]
The errors were from device `/dev/sdb` on host `os-sto-2`:

```
Mar 19 14:56:20 os-sto-2 kernel: sd 0:2:1:0: [sdb] tag#110 FAILED Result: hostbyte=DID_ERROR driverbyte=DRIVER_OK cmd_age=7s
Mar 19 14:56:20 os-sto-2 kernel: sd 0:2:1:0: [sdb] tag#110 CDB: Read(10) 28 00 0a c8 cd 00 00 01 80 00
Mar 19 14:56:20 os-sto-2 kernel: blk_update_request: I/O error, dev sdb, sector 180931840 op 0x0:(READ) flags 0x0 phys_seg 48 prio class 0
Mar 19 16:17:45 os-sto-2 kernel: sd 0:2:1:0: [sdb] tag#425 FAILED Result: hostbyte=DID_ERROR driverbyte=DRIVER_OK cmd_age=0s
Mar 19 16:17:45 os-sto-2 kernel: sd 0:2:1:0: [sdb] tag#425 CDB: Read(10) 28 00 0a c8 cd 00 00 01 80 00
Mar 19 16:17:45 os-sto-2 kernel: blk_update_request: I/O error, dev sdb, sector 180931840 op 0x0:(READ) flags 0x0 phys_seg 48 prio class 0
```

**Comment by tumido** [comment]
Interesting. I'm glad we have a wizzard like you on the team. :+1: :1st_place_medal:

Does that mean, we have a faulty device?

**Comment by larsks** [comment]
> Does that mean, we have a faulty device?

It may. It turns out this host happens to have a fourth physical disk installed and unused, but it's not exposed to the RAID controller. That means we can reboot the system, activate the spare drive, and swap it for the faulty one in Ceph.

Not going to do that today, but we can probably do that sometime next week. I'd like to figure out the correct way to do maintenance on a storage node like that, rather than just shooting it in the head like I did last time by accident :).

**Comment by tumido** [comment]
Closing as resolves, the faulty drive replacement has a separate issue: #236
