### ISSUE TITLE
Update openshift on zero cluster to 4.7.2

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#225]
There are a bunch of fixes in 4.7.2:

- https://access.redhat.com/errata/RHBA-2021:0678 (4.7.1)
- https://access.redhat.com/errata/RHBA-2021:0749 (4.7.2)

**Comment by tumido** [comment]
This can be done declaratively via `clsuterversion` resource on zero cluster or via ACM.

@randymgeorge  @cdoan1, is there a way how to bump the cluster version declaratively via ACM? Documentation mentions UI route only.

**Comment by larsks** [comment]
@tumido @HumairAK I would like to send the following out to the mailing list this afternoon:

```
Hello Operate First users,

We’re reaching out to you since you’re the users of the MOC OpenShift
cluster at zero.massopen.cloud. This message is important to you whether you
are a direct user of the OpenShift cluster or an ODH/Kubeflow user.

We are planning on a minor upgrade to OpenShift, from 4.7.0 to
4.7.2, on Monday, March 29, 2021. We do not anticipate any
interruptions as a result of this work, although it is possible there
may be a performance impact while the upgrade is taking place. We
expect the work to start around 9AM (US/Eastern) and complete by noon.

You can track the progress of this work in the following issues:

- https://github.com/operate-first/SRE/issues/225
- https://github.com/operate-first/apps/pull/421
```

**Comment by tumido** [comment]
@larsks sure, can you please:
1. Update the mailing list users with the latest user list from the zero
2.  post the message to the `#announcements` channel on slack, when you send the email? :slightly_smiling_face: 

The email content LGTM :+1: 

Thank you!

**Comment by larsks** [comment]
> Update the mailing list users with the latest user list from the zero

Did that earlier :)

> post the message to the #announcements channel on slack, when you send the email? slightly_smiling_face

Sure.

**Comment by HumairAK** [comment]
Email lgtm, we can use this email as a template for our update procedure as part of https://github.com/operate-first/SRE/issues/226

**Comment by larsks** [comment]
After the power outage was resolved, the controllers successfully updated to 4.7.2. At this point, the update seems stuck; no updates have happened on the worker nodes. I've asked internally on the `openshift-sme` mailing list for any suggestions, and I'm about to open a support case.

**Comment by larsks** [comment]
I have opened support case [02904866](https://access.redhat.com/support/cases/#/case/02904866) on this issue.

**Comment by HumairAK** [comment]
Closing this as the update was complete some time back, please re-open if needed.
