### ISSUE TITLE
SPIKE: Evaluate content from OSD team for sre

### ISSUE THREAD

**Issue by durandom** [operate-first/SRE#23]
Have a look at https://github.com/openshift/managed-cluster-config/tree/master/deploy/sre-prometheus
Maybe it has some interesting content for us, maybe the organization of files is inspiring

**Comment by hemajv** [comment]
I liked how they organized their alerts into separate prometheus rule files, for eg: https://github.com/openshift/managed-cluster-config/blob/master/deploy/sre-prometheus/100-sre-api-errors.PrometheusRule.yaml. 

I think we can adopt this to group our alerts based on the defined SLO/SLAs for our applications/services.

**Comment by tumido** [comment]
@hemajv can this issue be closed? I see this card in the **December 2020** column

**Comment by hemajv** [comment]
@tumido yes closing it out
