### ISSUE TITLE
Bare Metal Hosts Registration error

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#234]
All hosts are reporting registration error. Apparently there's no cluster alert for this.

```
Failed to get power state for node 861ada16-a145-4f51-bc7f-bed6e9388487. Error: Command '['ipmitool', '-I', 'lanplus', '-H', '10.0.17.34', '-L', 'ADMINISTRATOR', '-p', '623', '-U', 'mocadmin', '-R', '12', '-N', '5', '-f', '/tmp/tmp5r1ob2vc', 'power', 'status']' timed out after 60 seconds
```

![image](https://user-images.githubusercontent.com/7453394/112989753-8a1fdb00-9165-11eb-92c3-776b85d61aa9.png)

**Comment by larsks** [comment]
Restarting the `metal3` pod has successfully cleared the errors.
