### ISSUE TITLE
Ceph on Zero cluster is not healthy

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#235]
Cluster is reporting error on storage but both `NooBaa` and `StorageCluster` are reporting OK

https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/openshift-storage/noobaa.io~v1alpha1~NooBaa/noobaa
https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/openshift-storage/ocs.openshift.io~v1~StorageCluster/ocs-storagecluster

```
NAME                 AGE   PHASE   EXTERNAL   CREATED AT             VERSION
ocs-storagecluster   20d   Ready              2021-03-09T16:06:53Z   4.6.0

NAME     MGMT-ENDPOINTS                     S3-ENDPOINTS                       IMAGE                                                                                                            PHASE   AGE
noobaa   ["https://192.12.185.130:32669"]   ["https://192.12.185.132:31658"]   registry.redhat.io/ocs4/mcg-core-rhel8@sha256:bbd531eb4ec7faf7b5480599e7a7d908b41e99e5b5a853b3bed4e793efd65d4e   Ready   20d
```

Related to:
https://github.com/operate-first/alerts/issues/1375
https://github.com/operate-first/alerts/issues/1373

**Comment by tumido** [comment]
From within the ceph cluster I can see:
```
ceph> health
b'HEALTH_ERR 1 scrub errors; Possible data damage: 1 pg inconsistent\n'
```

**Comment by larsks** [comment]
The error is in pg 5.5:

```
sh-4.4# ceph health detail
HEALTH_ERR 1 scrub errors; Possible data damage: 1 pg inconsistent
OSD_SCRUB_ERRORS 1 scrub errors
PG_DAMAGED Possible data damage: 1 pg inconsistent
    pg 5.5 is active+clean+scrubbing+deep+inconsistent+repair, acting [7,3,5]
```

**Comment by tumido** [comment]
Yup, trying
```
sh-4.4# ceph pg repair 5.5
instructing pg 5.5 on osd.7 to repair
```

**Comment by tumido** [comment]
Resolved:

```
sh-4.4# ceph health   
HEALTH_OK
```

**Comment by tumido** [comment]
Seems like we need a new disc. It's the same device as last time:
https://github.com/operate-first/SRE/issues/224#issuecomment-802968591

**Comment by tumido** [comment]
Closing as the incident was resolved, ffr the disc device will be replaced

**Comment by HumairAK** [comment]
For others like myself who are not as savvy :)  

the commands above can be executed in the `rook-ceph-tools` pod by doing: 
```
oc rsh deployment/rook-ceph-tools
``` 

Ceph docs here are also a good reference: https://docs.ceph.com/en/latest/rados/operations/monitoring/#using-the-command-line
