### ISSUE TITLE
Improve service reliability via automated tests against the live Operate First environment

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#238]
Use RHODS test framework as a base and contribute to it, making it more versatile and usable against multitude of ODH environments, not just RHODS (ODH upstream and Operate First as well)

https://github.com/red-hat-data-services/ods-ci

**Comment by HumairAK** [comment]
@LaVLaS we're considering assigning an intern this task. We're considering using this framework to perform tests against our live odh environment. Could you recommend the best way to get started? I see the docs aren't fleshed out yet in the repo, are there live examples one could look at to get an idea of how to use this tooling?

**Comment by LaVLaS** [comment]
The [ods-ci](https://github.com/red-hat-data-services/ods-ci) relies on [Robot Framework]( https://robotframework.org/) with [SeleniumLibrary](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html) keywords to automate JupyterHub and JupyterLab.

Here is an example [testcase](https://github.com/red-hat-data-services/ods-ci/blob/master/tests/Tests/test-minimal-image.robot) that will spawn the minimal notebook image, git clone repo & open a notebook to verify that the appropriate python libraries are installed and working correctly

**Comment by HumairAK** [comment]
@larsks thank you!
