### ISSUE TITLE
[Docs] Add links to all available services (both for users and operations) on the operate-first website

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#25]
Services: 
Users:
- Jupyterhub 

Ops:
- Grafana
- Prometheus / Alertmanager
- ArgoCD 
- Incidents page (based on #19 would be just the link to the support repo)

**Comment by HumairAK** [comment]
This can tie back to #24 and be added on the flight page.

**Comment by hemajv** [comment]
https://odh-dashboard-opf-dashboard.apps.cnv.massopen.cloud/
We can include the above dashboard as page on the website

**Comment by HumairAK** [comment]
I've also added all the links [here](https://github.com/operate-first/odh/issues/10) for now for easy reference.

**Comment by tumido** [comment]
I think we should rather point to the dasboard (so we don't confuse downstream and upstream) and + a flight plan for each component.

**Comment by hemajv** [comment]
@tumido so the table you have in [this PR](https://github.com/operate-first/odh-moc-support/pull/28) which includes the columns `Component, Availability, Authentication`...is the flight plan, correct?

**Comment by tumido** [comment]
That's a very sparse light plan. :slightly_smiling_face:  I honestly don't know. It's more like a very poor status report. Let it be the first iteration and we can make it better going forward, WDYT?

**Comment by hemajv** [comment]
Yeah that sounds good to me :+1:

**Comment by hemajv** [comment]
https://github.com/operate-first/operate-first.github.io/pull/140

**Comment by HumairAK** [comment]
I think the dashbaord link introduced [here](https://github.com/operate-first/odh-moc-support/pull/28) works out well. Let's go with this.
