### ISSUE TITLE
Update our Sprint planning session to incorporate Epics

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#252]
To summarize from our last sprint planning discussion, we identified some ways in which we can improve our sprint planning. Key takeaways: 

- Incorporate milestones with time-frames that specify a concrete set of tasks (issues) and end goals/outcomes. The completion requirement for the milestone should be abundantly clear, with a reasonable time-frame set.

- A preliminary session for grooming the board, (done by @HumairAK  and possibly others), identifying new milestones, and state of current milestones and accomplishments with links to threads 

We talked about implementing milestones using labels, this is a venue to discuss this further or possible other solutions.

This issue can be marked closed when a suitable format for sprint planning is created and how to manage milestones. The framework should be defined in markdown and stored in git.

**Comment by HumairAK** [comment]
@durandom @4n4nd @tumido @hemajv @larsks

**Comment by HumairAK** [comment]
My initial thought was to do something like how argoproj does their milestones: https://github.com/argoproj/argo-cd/milestone/22 (instead of versions we would do regular words like "E2E CLO pipeline to loki") and then have the issues associated with this milestone to mark it complete. 

BUTT according to @tumido this is not cross repo

**Comment by tumido** [comment]
> BUTT according to @tumido this is not cross repo

According to many people it should :smile:

https://github.com/dear-github/dear-github/issues/93

**Comment by HumairAK** [comment]
So one suggestion is to just use "nested" projects: 
- Have one parent project called something like  "All Milestones" this is the one we will go through at a high level, during sprint planning. 
- Have child projects that are all linked back to "All Milestones" project 

Pros: 
- Cross repo 
- Each issue belongs to a project "milestone" with a nice progress bar (similar to repo milestones) 
- Milestones can be closed out 
- Milestones can be visually seen in a kanban like format in the "All Milestones" project, with a progress bar 

Cons: 
- Project milestones need to be "closed" out twice, one for closing the project, anodther for _dragging it to the done column_ in the "All Milestones" project. 
- Got to relink repos every time a new milestone is created (not necessarily a bad thing, a milestone does not need to always touch every repo) 

A live example of this can be found here: https://github.com/orgs/example-test-organization/projects

**Comment by HumairAK** [comment]
Going to implement these, but instead of "milestones" we will call it "Epics" so as not to be confused with github's native milestone functionality.

**Comment by HumairAK** [comment]
Added : https://github.com/orgs/operate-first/projects
