### ISSUE TITLE
Add runbooks to operate-first.cloud/

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#263]
Currently the runbooks are not rendered on the website, let's add them.

**Comment by tumido** [comment]
https://github.com/aicoe-aiops/data-science-workflows/pull/32#issuecomment-821248159

**Comment by HumairAK** [comment]
The kafka/JH runbooks were added, see: 
- https://github.com/operate-first/operate-first.github.io/pull/238
- https://github.com/operate-first/operate-first.github.io/pull/236
