### ISSUE TITLE
Ceph in Error state

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#268]
Similar to: #235

Ceph is reporting https://github.com/operate-first/alerts/issues/4002

```
sh-4.4# ceph status
  cluster:
    id:     895c1f68-fc4c-4355-a7bf-51c57c78d59b
    health: HEALTH_ERR
            1 scrub errors
            Possible data damage: 1 pg inconsistent
 
  services:
    mon: 3 daemons, quorum e,f,g (age 2d)
    mgr: a(active, since 3w)
    mds: ocs-storagecluster-cephfilesystem:1 {0=ocs-storagecluster-cephfilesystem-a=up:active} 1 up:standby-replay
    osd: 9 osds: 9 up (since 6d), 9 in (since 5w)
    rgw: 2 daemons active (ocs.storagecluster.cephobjectstore.a, ocs.storagecluster.cephobjectstore.b)
 
  task status:
    scrub status:
        mds.ocs-storagecluster-cephfilesystem-a: idle
        mds.ocs-storagecluster-cephfilesystem-b: idle
 
  data:
    pools:   10 pools, 368 pgs
    objects: 967.35k objects, 1017 GiB
    usage:   3.1 TiB used, 1.8 TiB / 4.9 TiB avail
    pgs:     367 active+clean
             1   active+clean+inconsistent
 
  io:
    client:   105 MiB/s rd, 35 MiB/s wr, 141 op/s rd, 425 op/s wr

sh-4.4# ceph health detail
HEALTH_ERR 1 scrub errors; Possible data damage: 1 pg inconsistent
OSD_SCRUB_ERRORS 1 scrub errors
PG_DAMAGED Possible data damage: 1 pg inconsistent
    pg 10.15 is active+clean+scrubbing+deep+inconsistent+repair, acting [0,5,3]
```

Attempting to repair pg 10.15

**Comment by tumido** [comment]
Seems like it's comming from `os-sto-2` node:

```
$ oc debug nodes/os-sto-2
Starting pod/os-sto-2-debug ...
To use host binaries, run `chroot /host`
Pod IP: 192.12.185.132
If you don't see a command prompt, try pressing enter.
sh-4.4# dmesg | egrep -i 'medium|i\/o error|sector|Prefailure'
[2018166.917886] megaraid_sas 0000:02:00.0: 9239 (672619461s/0x0001/FATAL) - Uncorrectable medium error logged for VD 01/1 at 1c8bf106 (on PD 01(e0x20/s1) at 1c8bf106)
[2018170.311575] megaraid_sas 0000:02:00.0: 9241 (672619464s/0x0001/FATAL) - Uncorrectable medium error logged for VD 01/1 at 1c8bf107 (on PD 01(e0x20/s1) at 1c8bf107)
[2028308.621939] blk_update_request: I/O error, dev sdb, sector 54090496 op 0x0:(READ) flags 0x0 phys_seg 16 prio class 0
[2139760.894920] blk_update_request: I/O error, dev sdb, sector 54090496 op 0x0:(READ) flags 0x0 phys_seg 9 prio class 0
[2150381.274598] blk_update_request: I/O error, dev sdb, sector 54090496 op 0x0:(READ) flags 0x0 phys_seg 16 prio class 0
```

**Comment by tumido** [comment]
`/dev/sdb` is the same device as last time.

@larsks @billburnseh  how can we raise a ticket to have that hard drive replaced?

/cc @durandom

**Comment by tumido** [comment]
Rebuild successful. Ceph is reporting `HEALTH_OK` again.

**Comment by tumido** [comment]
Related: https://github.com/operate-first/SRE/issues/236

**Comment by billburnseh** [comment]
Seems like a ticket is reasonable, Michael Daitzman should be able to advise if needed (seems to not be part of this repo, so adding Naved).
@naved001

**Comment by naved001** [comment]
iDrac does not report any failure (or predicted failure) for any drives on host `os-sto-2` so I am not sure if we want to replace the drive just yet.

There's another physical drive on that host that is not being used for anything (I don't think it will show up under `lsblk` since there's no corresponding virtual disk that's created on the RAID controller). You could use that drive to create an OSD and get rid of the problem drive/osd.

![image](https://user-images.githubusercontent.com/20113064/116107232-d84ece00-a680-11eb-8aa8-edaac57e9368.png)

In fact, all storage nodes have an additional physical drive that's not used. I guess if you don't use those for OSDs, they can serve as spares.

**Comment by tumido** [comment]
Please, let's discuss the drive replacement further in #236 @billburnseh @naved001
