### ISSUE TITLE
[Operate-first-users] OpenShift Cluster upgrade, scheduled for Monday 2021-04-26

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#269]
Hello Operate First users,

We are planning on an upgrade to the MOC/Zero cluster, from v4.7.2 to v4.7.6, on Monday 2021-04-26. We expect to start around 9AM EST and expect the upgrade to take approximately 3 Hours.

This update may cause some minor disruption for services hosted in the MOC Zero cluster, MOC Infra cluster should not be affected by this update.

Please let us know if you see any disruptions in any of the services.

Related links:
- https://github.com/operate-first/apps/pull/530

**Comment by HumairAK** [comment]
Also going to approve pending operators before starting upgrade, @tumido is doing that now: 
![image](https://user-images.githubusercontent.com/10904967/116088060-80f43200-a66f-11eb-9137-28fc2fac9645.png)

**Comment by HumairAK** [comment]
Also going to merge this: https://github.com/operate-first/apps/pull/546 afterwards before: https://github.com/operate-first/apps/pull/530

**Comment by tumido** [comment]
Logging operator is up to date now, 2 updates were applied.

**Comment by HumairAK** [comment]
> Also going to merge this: [operate-first/apps#546](https://github.com/operate-first/apps/pull/546) afterwards before: [operate-first/apps#530](https://github.com/operate-first/apps/pull/530)

https://github.com/operate-first/apps/pull/546 was applied (w/o reboot for changes to take affect)

**Comment by tumido** [comment]
Virtualization upgraded once successfully, pending second upgrade.
Metering upgraded twice - up to date.
Local storage upgraded twice - up to date now.

**Comment by tumido** [comment]
Container storage upgraded - up to date.
Only one last upgrade pending - Virtualization. All dependent object are already upgraded and reconciled, waiting on the upgrade process to notice it.

**Comment by tumido** [comment]
Correction, I've missed that: Container storage is still progressing:
![image](https://user-images.githubusercontent.com/7453394/116091553-3d1c1f80-a6a5-11eb-8eb1-13c43f6c2d6f.png)

**Comment by HumairAK** [comment]
Seeing multi-attach errors in a couple of namespaces, like openshift-image-registry and openshift-logging: 

```
Generated from kubelet on os-wrk-2
10 times in the last 20 minutes
MountVolume.MountDevice failed for volume "pvc-e4da30d7-0c33-45a2-a972-206b364e5797" : rpc error: code = Aborted desc = an operation with the given Volume ID 0001-0011-openshift-storage-0000000000000001-231ade62-80f2-11eb-adf5-0a580a81021a already exists
```

**Comment by tumido** [comment]
All affected PVCs are provided by Ceph - we need to wait for OCS to finish the upgrade

**Comment by tumido** [comment]
ceph upgrade is hanging on CPU:
We need to kick some pods maybe. I'll remove some completed pods elsewhere, hope it helps
![image](https://user-images.githubusercontent.com/7453394/116093084-abadad00-a6a6-11eb-90e1-acf164b0c5d0.png)

**Comment by tumido** [comment]
Cleaned up Completed and Failed pods - that freed the CPU in the cluster.

At the same time I've noticed that 2 nodes became "Scheduling disabled", no idea why. Investigating

**Comment by HumairAK** [comment]
There are various pods in the `openshift-pipelines` namespace that are stuck on terminating, as they will not evict it's causint failure of node draining for some of the cluster nodes. `os-sto-0` and `os-wrk-0`.

**Comment by tumido** [comment]
We had to clean up the pods manually.  by using `--force` only after deleting their parent replica set.

**Comment by HumairAK** [comment]
Nodes are successfully draining consecutively

**Comment by HumairAK** [comment]
screencap of events from os-wrk-2 -- I think the drains were initiated by: https://github.com/operate-first/apps/pull/546
![image](https://user-images.githubusercontent.com/10904967/116104688-a472a900-a67e-11eb-9a9f-827cbd4a69d0.png)

**Comment by tumido** [comment]
OCS nearly fully upgraded now:

![image](https://user-images.githubusercontent.com/7453394/116112930-55496a00-a6b8-11eb-89ef-d01e666fb93f.png)

**Comment by tumido** [comment]
Virtualization is waiting for the `os-sto-1` node to get ready to complete the upgrade.

**Comment by HumairAK** [comment]
`os-sto-1` was stuck for a while, but eventually moved on with the config update. We tried to restart the host machine via the ui, though it's not clear if that's what fixed it, or not (ui feedback here is minimal) 

![image](https://user-images.githubusercontent.com/10904967/116119994-0fc37780-a68d-11eb-916d-3b698e4227bd.png)

**Comment by HumairAK** [comment]
The ui visuals for the host machine reboot event: 
![image](https://user-images.githubusercontent.com/10904967/116120126-34b7ea80-a68d-11eb-970e-ec01dcad9c27.png)

**Comment by tumido** [comment]
OCS finished upgrading with the last node available again

**Comment by HumairAK** [comment]
Openshift Virt operator complaining about SA's being stale, re-installing subscription so the operator will re add them. (can't retrigger an install using OLM so readding subscription)

**Comment by tumido** [comment]
We had to uninstall the Virtualization operator and reinstall it. Note: removing operator leaves the resources untouched, so user workloads were not modified.

All operators upgraded now.

**Comment by HumairAK** [comment]
Merged: https://github.com/operate-first/apps/pull/530

Actual upgrade now commencing

**Comment by tumido** [comment]
Ceph storage is in `error` state now, investigating

**Comment by tumido** [comment]
Ceph had a monitor deployment for `os-sto-1` node scaled to zero. Maybe comes as a mistake from our manual drain of that node..

I've found out from looking at the other monitor pods and seeing it fail to elect a leader:
```
debug 2021-04-26 17:35:49.390 7f07dea1d700  0 mon.g@2(probing) e12 handle_command mon_command({"prefix":"config rm","name":"mgr","key":"mgr/rbd_support/a/mirror_snapshot_schedule"} v 0) v1
debug 2021-04-26 17:35:49.390 7f07dea1d700  0 log_channel(audit) log [INF] : from='mgr.5314811 10.131.0.125:0/1' entity='mgr.a' cmd=[{"prefix":"config rm","name":"mgr","key":"mgr/rbd_support/a/mirror_snapshot_schedule"}]: dispatch
debug 2021-04-26 17:35:50.089 7f07e3226700  1 mon.g@2(probing) e12 handle_auth_request failed to assign global_id
debug 2021-04-26 17:35:50.291 7f07e3226700  1 mon.g@2(probing) e12 handle_auth_request failed to assign global_id
debug 2021-04-26 17:35:50.569 7f07e3226700  1 mon.g@2(probing) e12 handle_auth_request failed to assign global_id
```

**Comment by tumido** [comment]
Ceph is reporting 0.157% data being degraded. It's recovering it right now.

**Comment by HumairAK** [comment]
machine-config in degraded state, reporting:
```
Unable  to apply 4.7.7: timed out waiting for the condition during  waitForDaemonsetRollout: Daemonset machine-config-daemon is not ready.  status: (desired: 9, updated: 1, ready: 9, unavailable: 0)
```

**Comment by HumairAK** [comment]
So the pods in https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/openshift-machine-config-operator/pods 
Were getting stuck in terminating, I had to manually delete them using the `--force` flag, and that allowed the cluster operator to go back to progressing state.

**Comment by HumairAK** [comment]
Monitoring also degraded: 
```
Failed to rollout the stack. Error: running task Updating Telemeter client failed: reconciling Telemeter client Prometheus Rule failed: updating PrometheusRule object failed: Internal error occurred: failed calling webhook "prometheusrules.openshift.io": Post "https://prometheus-operator.openshift-monitoring.svc:8080/admission-prometheusrules/validate?timeout=5s": x509: certificate signed by unknown authority
```
Similar issue, pod stuck in terminating, deleted 

```bash
$ oc delete pod prometheus-operator-b784f8595-bfxdp --force
```

FTR the pod was on os-ctrl-2

**Comment by HumairAK** [comment]
Following nodes went through draining, and now have their scheduling disabled: 

![image](https://user-images.githubusercontent.com/10904967/116137449-91bd9b80-a6a1-11eb-93d5-ad961590d544.png)

**Comment by HumairAK** [comment]
Worker nodes update completed, cluster-operators and master nodes left

**Comment by HumairAK** [comment]
os-ctrl-2 reporting: 
```
       Node os-ctrl-2 is reporting: "failed to update OS to
        quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6028a87f17b7ecb9fe4b5a9f1ab25999cd414924cbba5721320f14df9faec44a
        : with stdout output: : error running rpm-ostree rebase --experimental
        /run/mco-machine-os-content/os-content-843331219/srv/repo:10a6cbe55a0179f2650fbc72c8ab5e09c874a47e64ef1684edb09578b1cb1307
        --custom-origin-url
        pivot://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:6028a87f17b7ecb9fe4b5a9f1ab25999cd414924cbba5721320f14df9faec44a
        --custom-origin-description Managed by machine-config-operator: error:
        Transaction in progress: (null)\n: exit status 1"
```

From: https://console-openshift-console.apps.zero.massopen.cloud/k8s/cluster/machineconfiguration.openshift.io~v1~MachineConfigPool/master

**Comment by HumairAK** [comment]
os-ctrl-2 machien config issues continue to evade us, we've reached out to SME's for help, and will require further inquiry.

**Comment by HumairAK** [comment]
from @larsks 

> The support folks recommend that we just go ahead and force the machine config daemon on os-ctrl-2 to sync, and then see if the problem reproduces on another node. There is some data missing on os-ctrl-2 because of us killing off the mcd pod on that node.

**Comment by HumairAK** [comment]
We tried following the instructions here to foce a sync: https://access.redhat.com/solutions/5414371 with no success.

**Comment by HumairAK** [comment]
Cancel the last comment, we're trying force  syn again.

**Comment by HumairAK** [comment]
Looks like it worked, os-ctrl-2 upgraded successfully
os-ctrl-0 did as well (did not require manual intervention)

**Comment by HumairAK** [comment]
os-ctrl-1 crashed in the bios - a power cycle fixed it.

All control nodes have succesfully upgraded

**Comment by HumairAK** [comment]
Cluster successfully updated to 4.7.7, if there are any lingering issues please raise an issue.
