### ISSUE TITLE
Configure github auth token for alerting arch

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#27]
In https://github.com/operate-first/SRE/issues/19, we configured the GitHub alertmanager for handling Prometheus alerts. The GitHub alertmanager requires an auth token to be configured in order to open issues automatically in our repo for alerts being fired. We want to be able to configure the Thoth Sesheta bot for this.

Related PR: https://github.com/operate-first/apps/pull/68

**Comment by goern** [comment]
@harshad16 please generate an access token owned by @sesheta for this.

**Comment by harshad16** [comment]
surely, will co-ordinated with @hemajv  about this.

**Comment by hemajv** [comment]
Created a ksops encrypted secret based on the auth token provided by @harshad16:
https://github.com/operate-first/apps/pull/68/commits/7410c774ebf995308fa3fc8bb20d4bb5dc66b092

**Comment by hemajv** [comment]
We now have the GitHub alert manager configurations: https://github.com/operate-first/apps/tree/master/odh/base/monitoring
and we have the auth token for Sesheta configured for our MOC setup here: https://github.com/operate-first/apps/tree/master/odh/overlays/moc/monitoring
