### ISSUE TITLE
Incident management and post-mortems

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#283]
Further define how we should handle incidents in the SRE for easy search and exploration with the intention to speed up push to upstream.

Proposed system:
1. Incidents are filed in SRE repo
2. We have a (new) distinct label `incident`
3. Once incident is resolved we're gonna summarise the resolution and cause into a post-mortem comment in the issue
4. Add a new label to the issue called `post-mortem` to simplify the search for all issues with post-mortem documentation in place
5. Close the issue

**Comment by HumairAK** [comment]
related: https://github.com/operate-first/SRE/issues/276

**Comment by tumido** [comment]
@HumairAK does this mean we're adopting this without a question? It was just a proposal :smile:  

If so, I'll create a PR adding those labels to our repo config.

**Comment by HumairAK** [comment]
@tumido yeah I'm for it, tbh I don't really see an argument against it, this is something we ought to be doing anyway
