### ISSUE TITLE
[Automation] Should we settle on a single language for automation scripts? Which one?

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#299]
From the discussion @HumairAK started in operate-first/apps#635:

> one issue I'm seeing is right now we have a few scripts in bash, one in python (that @larsks has worked on) we will need to narrow down to one language if we are to wrap these, lest we start calling bash / python scripts from golang or something (yuck).

**Comment by larsks** [comment]
@HumairAK @tumido maybe something like https://github.com/larsks/opfcli?

**Comment by HumairAK** [comment]
@larsks yes, this is great! I was thinking cobra/viper as well -- I'll give this a look/test.

**Comment by HumairAK** [comment]
Can we have this moved to the operate-first org? Suggested options: 

1. move repo directly to this org 
2. create a repo, make a pr for review for discussion / implementation details

**Comment by larsks** [comment]
@HumairAK https://github.com/operate-first/opfcli/pull/1

**Comment by HumairAK** [comment]
We've settled on a golang cli, see https://github.com/operate-first/opfcli
