### ISSUE TITLE
[WIP] Github permissions to repos

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#303]
Lately we hit an issue with @larsks about permissions in our git organization.

In the current setup most of the org members are granted `triage` role on all of the repos. Surprisingly this `triage` role, doesn't allow you to assign projects to issues. Actually I don't see this permission even mentioned or documented in [this table](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level). By trial and error we discovered that the only `write`, `maintain` and `admin` roles can assign projects to issues.

On the other hand the `write` permissions allows users to create releases and push to upstream repositories among other things.  The permission gap between `triage` and `write` is huge. I'm hesitant to enable this for all org members without at least trying to limit the `write` role.

Experiments left for Thursday:
- Try setting [Project board permissions](https://docs.github.com/en/organizations/managing-access-to-your-organizations-project-boards/project-board-permissions-for-an-organization) because that's obviously completely unrelated to repo permission roles /s

**Comment by HumairAK** [comment]
> without at least trying to limit the write role.

Hrmm I can't find anything in their docs that says these levels can be customized, or even a way to add your own. For now we can just have an intermediate role that falls between `contributors-core` and `admin` ? Maybe a `project-curator` team with `write` access. Then we can be more selective on who goes in this team and gets this level of access.

**Comment by HumairAK** [comment]
bumping this for prioritizing this, as we have at least one individual who does not have sufficient permissions to properly curate issues/tasks/tags/releases etc.

**Comment by tumido** [comment]
Seems we don't have a choice than to create such extra team. :shrug: 

Creating subteam of `contributors-core` called [`curators`](https://github.com/orgs/operate-first/teams/curators

**Comment by tumido** [comment]
Should be resolved by creating the team mentioned above and granting users `write` on all repos.

**Comment by HumairAK** [comment]
@larsks can you confirm you have the needed access?

**Comment by larsks** [comment]
@HumairAK things look good after a quick check. :+1:
