### ISSUE TITLE
Enforce Noobaa storage class for all object buckets, deprecate RadosGW storage class

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#313]
Part of: https://github.com/operate-first/SRE/issues/312

RadosGW/Rook doesn't provide any metrics on bucket usage and consumption. In contrast Noobaa does.

Change/enforce storage class on ObjectBucketClaims:
Good: `openshift-storage.noobaa.io`
Forbidden: `ocs-storagecluster-ceph-rgw`

**Comment by larsks** [comment]
Can we enforce quotas on object storage (for either rgw or noobaa)?

**Comment by tumido** [comment]
@larsks  not right now. I've requested it (it's linked to all the rest issues as well :smile: ) https://github.com/rook/rook/issues/7906

**Comment by HumairAK** [comment]
We need to move current obc's from rgw to nooba, there are 3 active, one for thanos, one for loki and one for ci-pro-artifacts which is here: 
https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/opf-ci-prow/objectbucket.io~v1alpha1~ObjectBucketClaim/ci-prow-artifacts 

@harshad16 will be switching this to nooba

@4n4nd & @larsks are currently working on using s3 on the nfs server, per the chat: 

```
larsks  
... for access to s3 on the nfs server: s3 endpoint is <https://10.253.0.10:9000.. If you add an entry to /etc/hosts named "truenas" for that address and add https://gist.github.com/larsks/a26aa3b0513b5aa9893f70053a9dd94b as a trusted CA, you can validate the ssl certificate for https://truenas:9000. (edited) 
```
We will switch thanos/loki to this endpoint. 

Once these are transitioned I presume we can deprecate rgw route?

**Comment by 4n4nd** [comment]
@tumido currently the `openshift-storage.noobaa.io` storage classs for OBCs doesn't seem to be working ([related issue](https://github.com/operate-first/support/issues/243#issuecomment-842453954))

**Comment by tumido** [comment]
3 last OBCs remaining to convert to noobaa:

![image](https://user-images.githubusercontent.com/7453394/119649221-ae74fc80-be22-11eb-8d56-1bf60f9a81c4.png)

**Comment by HumairAK** [comment]
Some teams started using rgw due to nooba downtime, we need to get them to switch back to nooba.

**Comment by HumairAK** [comment]
bump

**Comment by tumido** [comment]
We might enforce this via https://github.com/operate-first/support/issues/248

**Comment by larsks** [comment]
This is no longer relevant; the smaug cluster only has a single object storage provider.
