### ISSUE TITLE
[INCIDENT][MOC/Cluster] - os-wrk-1 node is down

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#315]
Hello Operate First users,

We are investigating an ongoing incident affecting the `os-wrk-1` node on the MOC Zero cluster.

Impacted users: All MOC Zero cluster users

We will provide updates to this issue thread as the incident progresses.

**Comment by 4n4nd** [comment]
![Screenshot from 2021-05-17 16-05-53](https://user-images.githubusercontent.com/22333506/118549719-da5cf780-b729-11eb-9df2-666443175826.png)
This is resulting in JH pods being stuck in terminating

**Comment by tumido** [comment]
The node seems to be healthy again.

We should prioritize https://github.com/operate-first/SRE/issues/112 at some point

**Comment by HumairAK** [comment]
Yeah this was resolved yesterday evening, closing.
