### ISSUE TITLE
[blocked] Load grafana data source tokens from asecrets 

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#320]
Unblocked when implemented: https://github.com/integr8ly/grafana-operator/issues/189

To make `GrafanaDataSource`s fully between clusters, we need to be able to load SA bearer token from a secret instead of hardcoding the values into the data source.

_Originally posted by @tumido in https://github.com/operate-first/apps/pull/667#discussion_r636811853_

**Comment by michaelgarde** [comment]
This would be really useful in my opinion. If loading the secret from the same namespace, that the Grafana operator and GrafanaDataSource is deployed to was possible, i would be really happy.
