### ISSUE TITLE
[INCIDENT][MOC/Zero] - Update to system reserved memory for worker nodes resulting in node reboot.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#321]
Hello Operate First users,

We are investigating an ongoing incident affecting MOC Zero cluster. A recent change to the cluster has resulted in an unexpected rebooting of nodes. This may result in some workflows being interrupted unexpectedly.

Impacted users: all users of MOC Zero clusters

We will provide updates to this issue thread as the incident progresses.

**Comment by HumairAK** [comment]
The change in question: https://github.com/operate-first/apps/pull/673 

It seems the docs didn't indicate a node reboot would occur. 

We had some nodes stuck on draining nodes due to failure of pods being evicted (this is a known issue caused by poddisruption budgets by the istio-system pods)

**Comment by HumairAK** [comment]
Manually removing the pods causing nodes to get stuck on drain stage has helped move them along, we had to do something similar [here](https://github.com/operate-first/SRE/issues/269#issuecomment-826885200) before.

**Comment by HumairAK** [comment]
`os-wrk-1` the last node to reboot seems to be taking a lot longer than the others

**Comment by 4n4nd** [comment]
@larsks was able to hard reset the `os-wrk-1` and all nodes seem to be back up now :+1:
