### ISSUE TITLE
Configure repository permissions for https://github.com/operate-first/curator

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#323]
The https://github.com/operate-first/curator repository was recently transferred from the cci-moc organization to operate-first. We need to arrange for the following users to have write access to the repository:

- gagansk
- skanthed
- shruthi-raghuraman
- matankb

**Comment by tumido** [comment]
Should be all set now:

![image](https://user-images.githubusercontent.com/7453394/119641128-9f3d8100-be19-11eb-9d6f-258b8a98a61d.png)
