### ISSUE TITLE
Check on Ceph vs NFS performance

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#328]
I've opened https://access.redhat.com/support/cases/#/case/02937410 regarding the performance questions.

_Originally posted by @larsks in https://github.com/operate-first/SRE/issues/286#issuecomment-837384373_

**Comment by tumido** [comment]
Please see #286 for details on this issue. @larsks there seems to be an update on the support case saying the OCS nodes are under heavy load.

> The Planning documentation recommends for OCS-only nodes at least 30 Logical CPU, but your system is running more than only OCS

Is there anything we can do about it besides not using OCS? :grin:

**Comment by larsks** [comment]
This is no longer relevant.
