### ISSUE TITLE
Create UP alerts for odh services 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#33]
UP alerts need to be implemented for odh services, provided that these services provide these alerts.

**Comment by hemajv** [comment]
We currently have the "up" metric available for:

- [ ] Grafana
- [ ] Obervatorium
- [ ] JupyterHub
- [ ] Prometheus/Alertmanager

We can create suitable alerts for these to start off with

**Comment by hemajv** [comment]
Created a basic availability grafana dashboard: https://grafana-route-opf-monitoring.apps.cnv.massopen.cloud/d/r7WqgaBMk/operatefirst-availability?orgId=1&from=now-30m&to=now&refresh=1m
based on which we can configure the alerts
