### ISSUE TITLE
[MOC Zero] Upgrade to 4.7.13

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#330]
Tracking issue for OCP upgrade

**Comment by HumairAK** [comment]
upgrade started

**Comment by HumairAK** [comment]
Upgrade completed, @4n4nd deleted some additional pods during draining of nodes  stage as they had caused these said nodes to get stuck.

![image](https://user-images.githubusercontent.com/10904967/121229703-4aa7f600-c85c-11eb-8490-672ab3f8f222.png)

**Comment by HumairAK** [comment]
All jupyterhub pods seem to have disappeard from `opf-jupyterhub`

**Comment by tumido** [comment]
/close

The upgrade finished and was successful, we probably forgot to update and close this issue.
