### ISSUE TITLE
Share access to/make NFS cluster part of Operate First

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#334]
We need to be able to share access to the NFS cluster for operate first admins and oncalls - to be able to debug possible issues like: https://github.com/operate-first/SRE/issues/333

Possibly we should thing about making this cluster part of Operate First and make it's setup declarative as well.

/cc @HumairAK @larsks @4n4nd thoughts, ideas how to do that?

**Comment by larsks** [comment]
I think we need to be able to consume services over which we don't have direct administrative control. We're going to have the same issues if we consume ceph storage from NESE or from the MOC production ceph cluster after moving to new hardware.

**Comment by larsks** [comment]
(This also turns out to be a non-issue for #333, which is exclusively an OCP configuration issue).

**Comment by HumairAK** [comment]
bump
