### ISSUE TITLE
Evaluate OpenSLO

### ISSUE THREAD

**Issue by durandom** [operate-first/SRE#335]
Gordon Haff recommended

https://bitmason.blogspot.com/2021/06/openslo-with-ian-bartholomew.html
https://openslo.com/
https://github.com/OpenSLO/oslo/blob/main/CONTRIBUTING.md

Sounds like worth of an investigation

**Comment by tumido** [comment]
Seems very nice, I like that idea a lot. On the other hand they are "implementation neutral" which seems to mean "no implementation". Currently it's just a standard a yaml scheme, nothing more. There's no controller/operator to deploy etc.

It may be worth to keep an eye on it, but it doesn't seem to be that much useful as of now.
