### ISSUE TITLE
Ilana's departure invalidated pull-secrets

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#339]
Ilana left and together with her redhat account all pull secrets were invalidated. We need to propagate new pull secrets to curator and infra cluster and change the pull secrets used by ACM.

**Comment by larsks** [comment]
We should use a pull secret tied to the MOC subscriptions.

**Comment by tumido** [comment]
Do we use it on any cluster? Or do we need to generate a brand new secret?

**Comment by tumido** [comment]
FTR We have one now. @larsks generated a new pull secret associated with MOC account. :slightly_smiling_face:
