### ISSUE TITLE
[Incident][MOC Infra] metal-api is failing 

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#341]
https://console-openshift-console.apps.moc-infra.massopen.cloud/k8s/ns/openshift-machine-api/pods/metal3-7cc65f647-qk5qs/logs?container=metal3-machine-os-downloader

`metal3-7cc65f647-qk5qs` pod in `openshift-machine-api` is failing at `metal3-machine-os-downloader` init container with:

```
+ for i in $(seq ${MAX_ATTEMPTS})
+ curl -g --insecure --compressed -L --connect-timeout 120 -o rhcos-46.82.202011260640-0-openstack.x86_64.qcow2.gz http://provisioner.moc-infra.massopen.cloud:8080/rhcos-46.82.202011260640-0-openstack.x86_64.qcow2.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to provisioner.moc-infra.massopen.cloud port 8080: Connection refused
+ SLEEP_TIME=25
Download failed, retrying after 25 seconds...
+ echo 'Download failed, retrying after 25 seconds...'
+ sleep 25
+ [[ .gz == .gz ]]
+ gzip -d rhcos-46.82.202011260640-0-openstack.x86_64.qcow2.gz
gzip: rhcos-46.82.202011260640-0-openstack.x86_64.qcow2.gz: No such file or directory
```

Why is a bare metal install trying to download an openstack image?

Discovered while monitoring https://github.com/operate-first/SRE/issues/340

**Comment by tumido** [comment]
/cc @4n4nd @larsks 

note: This is not causing critical disruption of service, it's rather an inconvenience. It shouldn't be failing...

**Comment by larsks** [comment]
Note sure why it's failing, but note that isn't an OpenStack image. That's Red Hat CoreOS, which is the OS we're running on all the OpenShift nodes.

**Comment by larsks** [comment]
It looks like the metal3 api is trying contact a proxy on the provisioning host:

```
curl -g --insecure --compressed -L --connect-timeout 120 \
  -o rhcos-46.82.202011260640-0-openstack.x86_64.qcow2.gz \
  http://provisioner.moc-infra.massopen.cloud:8080/rhcos-46.82.202011260640-0-openstack.x86_64.qcow2.gz
```

That proxy no longer exists, and we probably shouldn't be depending on
it. I'll try to figure out what we need to change.
