### ISSUE TITLE
Zero cluster missing ACM subscription resource

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#342]
The Zero cluster is missing the ACM Subscription resource (`subscriptions.apps.open-cluster-management.io`). I don't know if this is related to #340 or not, but I ran into it when trying to test out a simple application deployment. Suggests on the ACM google chat are to try detaching/re-attaching the cluster. I'd like to do this tomorrow (Wednesday 6/16) and if it resolves both this issue and the pull secret propagation issues noted in #340.

**Comment by larsks** [comment]
@tumido

**Comment by tumido** [comment]
Sure let's try it. :slightly_smiling_face: It's weird that the CRD was never imported, while the Zero cluster was provisioned via ACM... Smells like a bug somewhere.

**Comment by tumido** [comment]
After poking the cluster together with @cdoan1 he unattached the Zero cluster from the hub and then he managed to purge all ACM related resources from the managed cluster. After re-attaching the cluster again things seems to behave. Closing as resolved.
