### ISSUE TITLE
[INCIDENT][MOC Zero] cluster unattached from from ArgoCD

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#343]
Fiddling with ACM for #342 made cluster unattached from ArgoCD.

**Comment by tumido** [comment]
changing `KlusterletAddonConfig` to:
```
  applicationManager:
    argocdCluster: true
```

resulted in:
![image](https://user-images.githubusercontent.com/7453394/122219384-ac490f80-ceaf-11eb-9017-8a1b57d16ff5.png)


trying to undo changes and try again

**Comment by tumido** [comment]
I've changed the bearer token manually to the value that should have been used by ACM. No idea why ACM uses different value. ArgoCD connection to Zero is restored now

/label resolved

**Comment by tumido** [comment]
relevant discussion in ACM: https://chat.google.com/room/AAAAWskU424/t9_9pjumqXs

**Comment by tumido** [comment]
FTR, ACM accomplishes ArgoCD connection by creating a `CLUSTER-cluster-secret` secret in `CLUSTER` namespace. This secret includes connection details and a token that should correspond to `klusterlet-addon-appmgr-token-*` from `open-cluster-management-agent-addon` namespace on the managed cluster `CLUSTER`.

ACM then copies the `CLUSTER-cluster-secret` from `CLUSTER` namespace to `argocd` namespace with slightly changed labels.

In our case the token used by ACM doesn't match the managed cluster at all. I have no idea where the token ACM used comes from.

Reference:
https://github.com/open-cluster-management/multicloud-operators-subscription/blob/aba98de50446db665350a30e3163d8fa0bfc6dae/pkg/controller/spoketoken/spoke_token_controller.go#L112-L114

**Comment by HumairAK** [comment]
This is now resolved, argocd correctly has the cluster detected.
