### ISSUE TITLE
Would you like to participate in our SRE on-call duty?

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#345]
Hey team!

I'd like to expand the on-call duty to more folks. While the current rotation that includes me, @4n4nd and @HumairAK works fine, it proved itself to be quite disruptive and time consuming for the 3 of us to be on constant rotation, holding us back from other duties.

On-call duty in operate first context means:
- Handle outside communication in Slack in case of outages and planned upgrades
- Helping out other community members in `#support` channel
- Serving onboarding requests and preparing PRs for them (using our cli tool) and reviewing existing onboarding PRs 

Our current schedule is to rotate the duty weekly. Person on duty is expected to be present on Slack on workdays during office hours (according to his/her timezone). On-call person is not expected to handle all queries and incidents themselves only, the rest of the team is always here to help. The main duty is to be the contact person for anybody in need. 

This issue should serve as a call to action and should spark discussion around who can be involved and is willing to step up and help us out. 

Taking the on-call responsibility provides you an exclusive opportunity to serve the community and gain more insight in Operate First's approach to cluster management, SRE and get to know various workloads operated by us.

**Comment by tumido** [comment]
I don't want to call out names, but some folks that might be interested from top of my head:
- @harshad16 
- @larsks 
- @Gregory-Pereira

**Comment by HumairAK** [comment]
I'd like to add that for this: 
> Helping out other community members in #support channel 

Can simply be tagging the right people who can answer questions, if the on call person is not versed in the subject matter.

**Comment by Gregory-Pereira** [comment]
I would love to volunteer!

**Comment by harshad16** [comment]
i would like to help out as well. :+1:

**Comment by rbo** [comment]
Please invite me too, I can't join every call but would like to listen sometimes :-)

**Comment by tumido** [comment]
@rbo this is not a meeting invite - it's rather a light version of: https://sre.google/sre-book/being-on-call/ 

I'll invite you to our sprint planning meetings, since we're missing you there. :slightly_smiling_face: 

I'm not sure if you still want to participate in the on-call duty as of now or if it was just a misunderstanding.

**Comment by rbo** [comment]
Got it, on-call duty maybe later. For now, I have enough tasks. Thanks for the clarification.

**Comment by HumairAK** [comment]
To move this forward, let's add the volunteers to the slack bot rotation

**Comment by tumido** [comment]
I need to merge https://github.com/tumido/slack-first/pull/114 and release so we can encrypt the members in a secret. :slightly_smiling_face: Give me today.
