### ISSUE TITLE
CPU Resources being capped for Zero cluster

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#346]
From the cluster compute resources dashboard: 

![image](https://user-images.githubusercontent.com/10904967/122594933-b4cb5280-d035-11eb-85c6-8e7ef32b85cd.png)

It seems to me we are basically reaching the cap of how much CPU requests we can make against the cluster. We have taken steps to reduce this number by adding quotas, and adding a JH culler. There is probably more we can be doing, like [here](https://github.com/operate-first/support/issues/240) and [here](https://github.com/operate-first/support/issues/222), but I doubt this will really alleviate the problem much. 

Yes, the cpu usage does not match up with the requests, and we're continuing to bring these in line with each other.

We are seeing more onboarding requests as time goes on, and not enough computer power to accomodate them. Looking for a discussion on what our strategy here should be, should we be pausing onboarding until more CPU cores can be freed up?

**Comment by HumairAK** [comment]
@durandom @tumido @4n4nd @larsks

**Comment by larsks** [comment]
> Looking for a discussion on what our strategy here should be, should we be pausing onboarding until more CPU cores can be freed up?

I think we should pause onboarding until (a) more CPUs core can be freed up or (b) we relocate the operate first cluster to new hardware.

**Comment by HumairAK** [comment]
I'm wondering what happens if the request commitment surpasses capacity for cores. With usage only at 1/4 of capacity, does this mean that requests can continue to be provisioned but may lead to unintended crashes if usage hits peak capacity?

**Comment by tumido** [comment]
![image](https://user-images.githubusercontent.com/7453394/122911142-464d0400-d357-11eb-82ab-4d6321972a9e.png)


I think we need to look into those biggest differences between usage and request. The top three namespaces reserve ~half of the cluster capacity.

1. @harshad16 what is `thoth-middletier-prod` running? can you please check on the quota and see if it can be downsized?
2. Openshift storage, if I remember correctly there was some dispute about reserving full nodes (that we can't afford) for it https://access.redhat.com/support/cases/#/case/02937410 I don't think we can do much about it...
3. Can we verify the culler in Jupyterhub namespace is doing it's job properly? If yes, we need to do a quick workaround for https://github.com/operate-first/support/issues/240 until we have exact data (this is moving forward on the DS side)

**Comment by HumairAK** [comment]
> Can we verify the culler in Jupyterhub namespace is doing it's job properly?

Seems to me like it is, from the pod logs: 

```
[I 210614 16:45:08 __init__:191] Culling server fmurdaca@redhat.com (inactive for 91:41:02)
[I 210614 16:45:08 __init__:191] Culling server asan@bu.edu (inactive for 91:40:13)
[I 210614 16:45:08 __init__:191] Culling server ayvijayk@redhat.com (inactive for 91:41:02)
[I 210614 16:45:08 __init__:191] Culling server sermann@redhat.com (inactive for 81:11:06)
[W 210614 16:45:18 __init__:241] Server ayvijayk@redhat.com is slow to stop
[W 210614 16:45:18 __init__:241] Server sermann@redhat.com is slow to stop
[I 210617 16:45:08 __init__:191] Culling server asanmukh@redhat.com (inactive for 97:54:50)
[W 210617 16:45:18 __init__:241] Server asanmukh@redhat.com is slow to stop
[I 210619 04:45:08 __init__:191] Culling server loubrieu@jpl.caltech.edu (inactive for 104:22:00)
[I 210619 04:45:08 __init__:191] Culling server bhaseman@redhat.com (inactive for 103:48:34)
[W 210619 04:45:20 __init__:241] Server bhaseman@redhat.com is slow to stop
[I 210620 16:45:09 __init__:191] Culling server eerlands@redhat.com (inactive for 92:50:44)
[I 210620 16:45:09 __init__:191] Culling server mcliffor@redhat.com (inactive for 92:07:59)
[W 210620 16:45:19 __init__:241] Server mcliffor@redhat.com is slow to stop
```
Let's discuss workaorund in: https://github.com/operate-first/support/issues/240

**Comment by harshad16** [comment]
@tumido , we run our data ingestion workflow in the `thoth-middletier-prod`, so at a time in a day, it consumes all the CPUs that we have requested for the namespace.
I would like to circle back to our conversation which we had in the beginning, suppose some namespace are consuming resources from time to time but not all, then we can keep on doing scaling down and scaling up of resources.
Also, it was mentioned to me that, resource request in quota is not the same as blocking the resources, then why is this an issue :smile:?

**Comment by tumido** [comment]
@harshad16 this is not directly tied to quota... quota should be fine and I think it's totally fine for you to have that big quota. The dashboard on screenshot above should be reporting the actual CPU request of pods and the actual usage of the pods... I don't know the actual result for this discrepancy, so I'm grasping the straws here and looking for help to get things sorted without disrupting your workloads :slightly_smiling_face:

**Comment by harshad16** [comment]
@tumido  thanks for the explanation , i got little confused earlier :sweat_smile: 
this a very excellent point, I will reduce the cpu request by pod based on consumption and try to optimize the consumption.

**Comment by HumairAK** [comment]
@harshad16 thank you! I was thinking, adjust the limits for the "peak" consumption, but reduce the requests to be better aligned with the usage. wdyt?

**Comment by durandom** [comment]
@Shreyanand can you create an EDA notebook outlining the diff between requests and usage on CPU?
And maybe come up with a function that suggests better "cpu requests" per pod.

cc @ilya-kolchinsky might help or might be interested

**Comment by tumido** [comment]
@durandom we just talked with @Shreyanand and he has some immediate results for us. We decided to eyeball some suitable profile values for the time being and once the analysis is finished, we'll readjust and change it once more to "proper" values.

**Comment by HumairAK** [comment]
Last sprint we have decided to pause onboarding, until we can gain newer hardware.

**Comment by tumido** [comment]
Considering each schedullable node (wrk/sto) has 32 cores available, we're still talking about 3-6 not-reserved cores now, that's still decent I think.

![image](https://user-images.githubusercontent.com/7453394/124774436-1a787380-df3e-11eb-8c29-0d6712cf82a3.png)

On the other hand, let's consider we have to rebalance the cluster in case we have an outage on a node. We're barely able to fit the current load on the remaining nodes (if we don't consider ceph pods, because of affinity to given nodes).

This is border line critical issue.
