### ISSUE TITLE
Create shared Bitwarden

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#363]
Based on https://github.com/operate-first/blueprint/issues/92#issuecomment-901120449

**Comment by rbo** [comment]
Created a group [operate-first](https://rover.redhat.com/groups/group/operate-first), required for a bitwarden collection.
Owner of the group:
- @tumido
- @goern 
- @durandom 
- @rbo 

Please add all Red Hatters who need access to the bitwarden. 

Requested bitwarden collection via [RITM0970441](https://redhat.service-now.com/surl.do?n=RITM0970441).

**Comment by rbo** [comment]
The collection is available added some hetzner/rick cluster related information.

**Comment by rbo** [comment]
@tumido tested the access, works very well.
