### ISSUE TITLE
[INCIDENT][MOC/Zero] Nodes down

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#372]
Hello Operate First users,

We are investigating an ongoing incident affecting nodes not being available on MOC Zero cluster. This causes pressure on the remaining nodes making the cluster slower than usual.

![image](https://user-images.githubusercontent.com/7453394/131843033-4d22f8aa-2d7b-4bec-8c42-90976fcd4ff4.png)

**Comment by HumairAK** [comment]
Closing this incident without resolution as Zero cluster is not a high priority any more.
