### ISSUE TITLE
Upgrade ArgoCD to the current release (2.1.2)

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#385]
Let's upgrade our ArgoCD installation. This will get us faster syncing
with less memory, the ability to use ApplicationSets, and better
repository configuration options (e.g. for private repos).

**Comment by larsks** [comment]
We should also ensure that we bundle `kustomize` 4.3.0 or later in order to avoid https://github.com/kubernetes-sigs/kustomize/issues/4183

**Comment by larsks** [comment]
@HumairAK where are the sources for our customized argocd docker image (`quay.io/operate-first/argocd`)? I don't see a likely looking repository here in the operate-first organization.

**Comment by larsks** [comment]
Also, is the process of rolling out the upgrade going to be...

1. Edit `argocd/base/kustomization.yaml` and change the ref on the github link
2. Manually inspect all the patches and other resources to confirm that they still look sane?

**Comment by larsks** [comment]
> @HumairAK where are the sources for our customized argocd docker image (quay.io/operate-first/argocd)? I don't see a likely looking repository here in the operate-first organization.

Maybe https://github.com/operate-first/continuous-deployment?

**Comment by HumairAK** [comment]
Just linking here for future ref, the questions above should be answered by this doc: https://github.com/operate-first/apps/blob/master/docs/argocd/update_argocd.md
