### ISSUE TITLE
Democratic CSI Driver on Smaug timing out 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#386]
The democratic CSI controller keeps crashing due to time outs. 

See the controller pod [here](https://console-openshift-console.apps.smaug.na.operate-first.cloud/k8s/ns/democratic-csi/pods). 

From the csi driver container logs: 

```
{"service":"democratic-csi","level":"error","message":"handler error - driver: FreeNASSshDriver method: Probe error: Error: Timed out while waiting for handshake"}
{ code: 13, message: 'Error: Timed out while waiting for handshake' }
{"service":"democratic-csi","level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"_events\":{},\"_eventsCount\":1,\"call\":{},\"cancelled\":false,\"metadata\":{\"_internal_repr\":{\"user-agent\":[\"grpc-node/1.24.0-pre1 grpc-c/8.0.0 (linux; chttp2; game)\"]},\"flags\":0},\"request\":{}}"}
running server shutdown, exit code: SIGTERM

```

**Comment by larsks** [comment]
It doens't appear to be a general connectivity problem; I ran the following playbook on all the nodes:

```
- hosts: all
  gather_facts: false
  tasks:
    - command: >-
        ping -c2 10.253.0.10
```

Which returns:

```
Executing playbook check-connectivity.yaml

- all on hosts: all -

[...]

- Play recap -
  oct-03-00-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-01-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-03-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-04-compute          : ok=0    changed=0    unreachable=0    failed=1    rescued=0    ignored=0   
  oct-03-07-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-08-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-09-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-10-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-11-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-12-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-13-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-14-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-15-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-17-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-19-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-20-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-21-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-22-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-23-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-24-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-25-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-26-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-27-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-28-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-29-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   
  oct-03-31-compute          : ok=1    changed=1    unreachable=0    failed=0    rescued=0    ignored=0   

```

Which means everything can reach the NFS server, which is good news.
That suggests any problems are just a driver configuration problem.

**Comment by larsks** [comment]
There's a routing issue on smaug that I don't understand. I've opened up https://access.redhat.com/support/cases/#/case/03038089 with questions. The text of the case is:

> We need to access services on a private network (10.253.0.0/23) on
> vlan 210 from within pods on our OpenShift cluster. We have added an
> interface on the worker nodes with an address on this network by
> adding a tagged port to br-ex:
> 
>     nmcli c add type ovs-port conn.interface nfs master br-ex ovs-port.tag 210 con-name ovs-port-nfs
>     nmcli c add type ovs-interface slave-type ovs-port conn.interface nfs master ovs-port-nfs con-name ovs-if-nfs ipv4.method auto
> 
> This results in an interface that correctly configures an ip address:
> 
>     [root@oct-03-23-compute /]# ip addr show nfs
>     816: nfs: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default qlen 1000
>         link/ether 7e:b1:db:34:54:63 brd ff:ff:ff:ff:ff:ff
>         inet 10.253.0.57/23 brd 10.253.1.255 scope global dynamic noprefixroute nfs
>            valid_lft 3126sec preferred_lft 3126sec
>         inet6 fe80::ef4b:63c2:abd1:81d1/64 scope link noprefixroute
>            valid_lft forever preferred_lft forever
> 
> This results in a routing table that looks like:
> 
>     default via 128.52.60.1 dev br-ex proto dhcp metric 100
>     10.0.0.0/16 dev eno1 proto kernel scope link src 10.0.0.42 metric 101
>     10.128.0.0/14 via 10.129.8.1 dev ovn-k8s-mp0
>     10.129.8.0/23 dev ovn-k8s-mp0 proto kernel scope link src 10.129.8.2
>     10.253.0.0/23 dev nfs proto kernel scope link src 10.253.0.57 metric 800
>     128.52.60.0/22 dev br-ex proto kernel scope link src 128.52.62.145 metric 100
>     169.254.169.0/30 via 128.52.60.1 dev br-ex
>     172.30.0.0/16 via 128.52.60.1 dev br-ex mtu 9020
> 
> However, when we attempt to access a service at 10.253.0.10 from
> within a pod, we see the query leave the node with the incorrect
> origin address. On worker oct-03-23-compute, we see that br-ex is
> associated with device enp4s0f0np0:
> 
>     [root@oct-03-23-compute /]# ovs-vsctl list-ports br-ex
>     enp4s0f0np0
>     nfs
>     patch-br-ex_oct-03-23-compute-to-br-int
> 
> Running tcpdump on that interface while attempting to access
> https://10.253.0.10/ from within a pod shows:
> 
>     / # tcpdump -i enp4s0f0np0 -n -e host 10.253.0.10
>     19:13:37.734688 00:0f:53:29:80:10 > 54:1e:56:d9:6a:c0, ethertype IPv4 (0x0800), length 74: 128.52.62.145.52686 > 10.253.0.10.443: Flags [S], seq 761580849, win 26940, options [mss 8980,sackOK,TS val 2784382730 ecr 0,nop,wscale 7], length 0
> 
> Here we see it using the origin address of br-ex, rather than the
> origin of the interface on vlan 210. The src MAC address in the above
> output doesn't match anything I recognize, and the destination address
> matches br-ex:
> 
>     / # ip addr show br-ex
>     12: br-ex: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9120 qdisc noqueue state UNKNOWN qlen 1000
>         link/ether 00:0f:53:29:80:10 brd ff:ff:ff:ff:ff:ff
>         inet 128.52.62.145/22 brd 128.52.63.255 scope global dynamic noprefixroute br-ex
>            valid_lft 639sec preferred_lft 639sec
>         inet6 fe80::78e9:a263:87a7:469f/64 scope link noprefixroute
>            valid_lft forever preferred_lft forever
> 
> This seems to be specific to OpenShift; if I spawn a podman pod on the
> same worker node, it is able to access the private network without a
> problem:
> 
>     [root@oct-03-23-compute /]# podman run -it --rm fedora:34 bash
>     Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
>     [...]
>     [root@059b5927ddf4 /]# curl -k https://10.253.0.10/
>     <html>
>     <head><title>302 Found</title></head>
>     <body>
>     <center><h1>302 Found</h1></center>
>     <hr><center>nginx</center>
>     </body>
>     </html>
>     [root@059b5927ddf4 /]#
> 
> How we we configure things so our OpenShift pods are able to access
> this network?

**Comment by naved001** [comment]
@larsks wondering why did you close this? is this being tracked elsewhere?

**Comment by larsks** [comment]
It looks like we've hit https://bugzilla.redhat.com/show_bug.cgi?id=1996108. There is an ugly workaround available in the bz.

 Possibly we could switch to the openshift sdn driver; there are rollback instructions in https://docs.openshift.com/container-platform/4.8/networking/ovn_kubernetes_network_provider/rollback-to-openshift-sdn.html, but it's not clear if we can use that without having previously been using openshift-sdn.

**Comment by larsks** [comment]
Solved by switching to OpenShiftSDN.
