### ISSUE TITLE
Convert `sre` content to Jupyter Notebook

### ISSUE THREAD

**Issue by quaid** [operate-first/sre#39]
We need this done and looking clean by 08:00 am EDT on Tuesday 25 October.

@schwesig are you available to help me with this? I would start the PR but then I'd end up down the rabbit hole.

We can check with @lisa for the table of contents, and @jeremyeder wants to keep an eye on this.

**Comment by schwesig** [comment]
- [x] convert operate-first/sre to a jupyter notebook
- [ ] create a link on the operate-first.cloud website

**Comment by schwesig** [comment]
created the jbook, tested it locally, all fine.
need to activate and script the publishing workflow.

**Comment by jeremyeder** [comment]
you have this staged anywhere we can review?

**Comment by schwesig** [comment]
in my fork, working on the PR
need to activate some background switches
https://github.com/schwesig/sre/tree/20221024_createjnb

**Comment by schwesig** [comment]
the jupyter book should be deployed on
https://www.operate-first.cloud/sre/
the workflow went through fine
https://github.com/operate-first/sre/actions/runs/3317029147

but it isn't ... I need to check again all details

**Comment by quaid** [comment]
Let's do one tweak while you're at it -- make the path to /sig-sre/ so the URL is https://operate-first.cloud/sig-sre/

**Comment by schwesig** [comment]
> Let's do one tweak while you're at it -- make the path to /sig-sre/ so the URL is https://operate-first.cloud/sig-sre/

unfortunately, it is not as easy (i couldn't find an easy way, help appreciated) to freely change the /sig to /sig-sre/
publishing with github pages is pretty hard coded to the name of the repo.

everything behind the repo name is free of choice
example
operate-first.cloud/sre/what-i-like
but operate-first.cloud/sre is fix.

my current recommandation, hence the time, stay with sre,
and using the shortener to use sig-sre

all prepared here
https://github.com/operate-first/sre/issues/40#issuecomment-1290177172

https://op1.st/sig-sre working --> https://www.operate-first.cloud/sre
