### ISSUE TITLE
ACM resources are not playing well with ArgoCD

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#391]
As you can see here: https://argocd.operate-first.cloud/applications/acm-infra 

Problem 1: 
ArgoCD seems to want to prune this resource `ManagedClusterInfo` which is created by acm, probably because it's adding the `app.kubernetes.io/instance: acm-infra` label, and we haven't added it in git

Problem 2:
There's also the `ManagedClusterSet` we have deployed called `argocd-managed` which will not sync because: 

```
the server does not allow this method on the requested resource
```
I added this label manually...and it seemed to acknowledge this resource as now part of the app...so I guess that worked as a workaround. 

Problem 3: 
similar to above, but the `curator` `managed clsuter` resource will not allow argocd or myself to add the instance label, reporting the same error: 
```
the server does not allow this method on the requested resource
```

Problem 4: 
The octo-secret keeps getting overwritten? it won't sync. Guessing acm is overwriting it.

**Comment by tumido** [comment]
I think some pointers can be found here: https://github.com/noseka1/multicluster-management-rhacm-argocd#why-is-argo-cds-auto-prune-disabled-in-this-repo

At least hopefully a partial fix: https://github.com/operate-first/apps/pull/1074

**Comment by HumairAK** [comment]
the only thing remaining is the octo aws secret which is not syncing

**Comment by HumairAK** [comment]
ACM app is now synced
