### ISSUE TITLE
Update all docs with mention of zero cluster

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#403]
We have various docs spread around this org that mention the zero cluster, these should be all updated to either: 

1) remove these mentions
2) update them to reflect the new smaug cluster instead (if applicable) 

We can start with the `support` readme found here: https://github.com/operate-first/support

Please link other docs in this thread that also need to be updated.

**Comment by margarethaley** [comment]
# Documents to update

## [Support](https://github.com/operate-first/support)
- [ ] [readme.md](https://github.com/operate-first/support#readme)
- [ ] [onboarding_to_cluster.md](https://github.com/operate-first/support/blob/main/docs/onboarding_to_cluster.md)
- [ ] [claiming_object_store.md](https://github.com/operate-first/support/blob/main/docs/claiming_object_store.md)
- [ ] [onboarding_to_argocd.md](https://github.com/operate-first/support/blob/main/docs/onboarding_to_argocd.md)
- [ ] [trino_superset_user_guide.md](https://github.com/operate-first/support/blob/main/docs/trino_superset_user_guide.md)
- [ ] [kubeflow readme.md](https://github.com/operate-first/support/tree/main/docs/kubeflow)
- [ ] [odh readme.md](https://github.com/operate-first/support/tree/main/docs/odh)

## [SRE](https://github.com/operate-first/SRE)
- [ ] [dashboards readme.md](https://github.com/operate-first/SRE/tree/master/dashboards)
- [ ] [configure_prometheus_alerts.md](https://github.com/operate-first/SRE/blob/master/incident-management/configure-prometheus-alerts.md)
- [ ] [jupyterhub.md](https://github.com/operate-first/SRE/blob/master/runbooks/jupyterhub.md)
- [ ] [kafka.md](https://github.com/operate-first/SRE/blob/master/runbooks/kafka.md)
- [ ] [superset.md](https://github.com/operate-first/SRE/blob/master/runbooks/superset.md)

## [Apps/docs]()
### Argocd
- [ ] [add_application.md](https://github.com/operate-first/apps/blob/master/docs/argocd/add_application.md)
### Kubeflow
- [ ] [pipelines readme.md](https://github.com/operate-first/apps/tree/master/docs/kubeflow/kubeflow-pipelines)
- [ ] [dashboard readme.md](https://github.com/operate-first/apps/tree/master/docs/kubeflow/kubeflow-dashboard)
### Observatorium
- [ ] [loki readme.md](https://github.com/operate-first/apps/tree/master/docs/observatorium/loki)
- [ ] [add_loki_grafana_datasource.md](https://github.com/operate-first/apps/blob/master/docs/observatorium/loki/add_loki_grafana_datasource.md)
- [ ] [thanos readme](https://github.com/operate-first/apps/tree/master/docs/observatorium/thanos)
### ODH
- [ ] [grafana readme.md](https://github.com/operate-first/apps/tree/master/docs/odh/grafana)
- [ ] [kafka readme.md](https://github.com/operate-first/apps/tree/master/docs/odh/kafka)
- [ ] [add_kafka_topics.md](https://github.com/operate-first/apps/blob/master/docs/odh/kafka/add_kafka_topics.md)
- [ ] [add_kafka_users.md](https://github.com/operate-first/apps/blob/master/docs/odh/kafka/add_kafka_users.md)
- [ ] [prometheus readme.md](https://github.com/operate-first/apps/tree/master/docs/odh/prometheus)

**Comment by carlosGimeno** [comment]
After reviewing all of the documents listed above, I found that most of these have already been updated but there are two files that needed to be modified (under the SRE repo, dashboards/readme.md and configure_prometheus_alerts.md). I have also made a PR request with the proposed updates to these 2 files.

**Comment by HumairAK** [comment]
awesome thanks @carlosGimeno feel free to close this issue once the pr is merged.
