### ISSUE TITLE
Write docs on how to use s3cmd or minio cli to access object storage

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#427]
It's not exactly obvious how one can access their object storage (buckets) using a cli tool, we have had to explain this already [here](https://github.com/operate-first/support/issues/103#issuecomment-804830427) once before, and the endpoint is in an inaccessible namespace (openshift-storage). So let's provide some docs with simple easy steps that users can follow.

**Comment by larsks** [comment]
I've removed "ceph bucket" from the title and description, since at least on Smaug object storage is provided by noobaa, not ceph.

**Comment by HumairAK** [comment]
woops, thanks @larsks !
