### ISSUE TITLE
[INCIDENT][SMAUG CLUSTER] - OCP worker nodes are down

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#430]
Hello Operate First users,

We are investigating an ongoing incident affecting the OCP worker nodes for the `Smaug` cluster.

Impacted users: all Smaug users 

We will provide updates to this issue thread as the incident progresses.

**Comment by larsks** [comment]
API access is up and running, and the ingress routers appear to be running:

```
$ oc -n openshift-ingress get pod
NAME                              READY   STATUS    RESTARTS   AGE
router-default-5b5d9b9f55-dlhdc   1/1     Running   0          69d
router-default-5b5d9b9f55-jl7sr   1/1     Running   0          69d
```

**Comment by larsks** [comment]
Access to pod logs appears to broken:

```
$ oc -n openshift-ingress logs router-default-5b5d9b9f55-dlhdc
Error from server: Get "https://128.52.62.241:10250/containerLogs/openshift-ingress/router-default-5b5d9b9f55-dlhdc/router": dial tcp 128.52.62.241:10250: connect: no route to host
```

**Comment by larsks** [comment]
All of the compute nodes are in state `NotReady`.

**Comment by larsks** [comment]
@hakasapl reports:

> I can reach OCT1,2,3,4 but not HUB-3 which links those with the back so something is up with that switch

**Comment by larsks** [comment]
@naved001 @hakasapl these are the oct-3 nodes that are unreachable:
```
- name: oct-03-00-compute
  address: 128.52.62.217
- name: oct-03-01-compute
  address: 128.52.62.216
- name: oct-03-03-compute
  address: 128.52.62.213
- name: oct-03-04-compute
  address: 128.52.62.233
- name: oct-03-07-compute
  address: 128.52.62.236
- name: oct-03-08-compute
  address: 128.52.62.234
- name: oct-03-09-compute
  address: 128.52.62.194
- name: oct-03-10-compute
  address: 128.52.62.241
- name: oct-03-11-compute
  address: 128.52.62.204
- name: oct-03-12-compute
  address: 128.52.62.134
- name: oct-03-13-compute
  address: 128.52.62.168
- name: oct-03-14-compute
  address: 128.52.62.164
- name: oct-03-15-compute
  address: 128.52.62.235
- name: oct-03-17-compute
  address: 128.52.62.195
- name: oct-03-19-compute
  address: 128.52.62.240
- name: oct-03-20-compute
  address: 128.52.62.242
- name: oct-03-21-compute
  address: 128.52.62.237
- name: oct-03-22-compute
  address: 128.52.62.238
- name: oct-03-23-compute
  address: 128.52.62.145
- name: oct-03-24-compute
  address: 128.52.62.246
- name: oct-03-25-compute
  address: 128.52.62.227
- name: oct-03-26-compute
  address: 128.52.62.245
- name: oct-03-27-compute
  address: 128.52.62.244
- name: oct-03-28-compute
  address: 128.52.62.243
- name: oct-03-29-compute
  address: 128.52.62.197
- name: oct-03-31-compute
  address: 128.52.62.239
```

**Comment by larsks** [comment]
It looks like the problem may have self-resolved. @@hakasapl reports the switch is reachable again, and the nodes are become `Ready`.

**Comment by larsks** [comment]
These nodes are still uncreachable:

```
oct-03-01-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-07-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-09-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-11-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-12-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-19-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-20-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-22-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-24-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-27-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-28-compute   NotReady   worker   105d   v1.21.1+38b3ecc
oct-03-31-compute   NotReady   worker   105d   v1.21.1+38b3ecc
```

**Comment by larsks** [comment]
I'm going to try rebooting one of the nodes that hasn't recovered. It's possible that the nodes that are still down have simply lost their dhcp lease. Once this is resolved we should:

- [ ] Verify lease lifetime on this network (and increase if it's too short)

**Comment by larsks** [comment]
I rebooted `oct-03-19-compute` and it seems to have rejoined the cluster. That may be the solution for the remaining nodes.

**Comment by larsks** [comment]
I've confirmed that the DHCP lease time on this network is only 1 hour:

```
[root@oct-03-19-compute ~]# nmcli c show enp4s0f0np0  | grep dhcp_lease_time
DHCP4.OPTION[1]:                        dhcp_lease_time = 3600
```

That's probably why these nodes aren't re-connecting after the outage.

**Comment by larsks** [comment]
@naved001 can you open an issue with the appropriate folks to increase the lease time on this network? Maybe to 12 hours? We want it long enough that a small outage doesn't cause nodes to lose their lease, but short enough that booting up a bunch of ephemeral vms won't exhaust the pool for longer periods.

**Comment by naved001** [comment]
I don't know how they would feel about making existing leases be static given we have static range available for that purpose. It doesn't hurt to ask, would we need to share the mac addresses of these hosts? I can also ask them if they could increase the lease time.

**Comment by naved001** [comment]
Even if they make the lease static, we would still have to have a longer lease time, right?

**Comment by HumairAK** [comment]
Console looks like it's gone down again.

**Comment by HumairAK** [comment]
It's back again `¯\_(ツ)_/¯`

**Comment by larsks** [comment]
>  It doesn't hurt to ask, would we need to share the mac addresses of these hosts?

We would, yes.

> Even if they make the lease static, we would still have to have a longer lease time, right?

Yes. And in fact in that case the lease could be *much* longer (like, on the order of a month), because it would only apply to that specific node.

**Comment by durandom** [comment]
> It's back again `¯\_(ツ)_/¯`

It's flaky. It didnt work this morning, then came back and now it's gone again. While it was back, my workloads were still running, if that helps to diagnose the issue

**Comment by larsks** [comment]
# IF YOU ARE REPORTING CONSOLE ACCESS PROBLEMS

Please provide the following information:

- Are you able to access the console from another location? E.g., if you log into `shell.bos.redhat.com` (or any other system not on the same network provider as your local machine), can you access the console with `curl -k https://console-openshift-console.apps.smaug.na.operate-first.cloud`?
- If console access works from elsewhere but does not work from your local system, please include the output of running `traceroute console-openshift-console.apps.smaug.na.operate-first.cloud` on your local system.

**Comment by durandom** [comment]
the IP packets are going through, but nobody's answering

```
❯ traceroute console-openshift-console.apps.smaug.na.operate-first.cloud
traceroute to console-openshift-console.apps.smaug.na.operate-first.cloud (128.52.60.32), 64 hops max, 52 byte packets
 1  10.5.0.1 (10.5.0.1)  17.522 ms  16.707 ms  23.851 ms
 2  196.240.57.233 (196.240.57.233)  21.567 ms  37.324 ms  20.907 ms
 3  196.244.72.249 (196.244.72.249)  21.447 ms  28.876 ms  22.763 ms
 4  bei-b1-link.ip.twelve99.net (62.115.179.190)  19.832 ms  26.577 ms  19.503 ms
 5  hbg-bb3-link.ip.twelve99.net (62.115.139.8)  27.045 ms  33.478 ms  29.947 ms
 6  hbg-b2-link.ip.twelve99.net (62.115.120.71)  35.930 ms *  34.195 ms
 7  be3045.rcr01.b015763-1.ham01.atlas.cogentco.com (130.117.14.245)  27.066 ms  28.815 ms  25.100 ms
 8  be2772.ccr42.ham01.atlas.cogentco.com (154.54.72.5)  33.398 ms  26.041 ms  24.476 ms
 9  be2816.ccr42.ams03.atlas.cogentco.com (154.54.38.209)  38.540 ms  31.900 ms  55.172 ms
10  be12488.ccr42.lon13.atlas.cogentco.com (130.117.51.41)  117.923 ms  126.893 ms  127.984 ms
11  be2490.ccr42.jfk02.atlas.cogentco.com (154.54.42.85)  118.566 ms  133.200 ms  122.263 ms
12  be2317.ccr41.jfk02.atlas.cogentco.com (154.54.30.185)  122.592 ms  114.307 ms  119.433 ms
13  be2359.ccr42.jfk02.atlas.cogentco.com (154.54.43.110)  124.256 ms
    dmz-rtr-1-external-rtr-3.mit.edu (18.0.161.13)  104.857 ms
    38.104.186.186 (38.104.186.186)  117.563 ms
14  dmz-rtr-1-external-rtr-3.mit.edu (18.0.161.13)  115.286 ms  116.677 ms  115.183 ms
15  dmz-rtr-2-dmz-rtr-1-2.mit.edu (18.0.162.6)  125.530 ms
    38.104.186.186 (38.104.186.186)  110.736 ms
    dmz-rtr-2-dmz-rtr-1-2.mit.edu (18.0.162.6)  118.915 ms
16  mitnet.core-1-ext.csail.mit.edu (18.0.162.142)  122.277 ms  114.256 ms
    dmz-rtr-1-external-rtr-3.mit.edu (18.0.161.13)  112.988 ms
17  dmz-rtr-2-dmz-rtr-1-2.mit.edu (18.0.162.6)  117.935 ms
    core-1-ext.holyoke.csail.mit.edu (128.30.0.234)  130.007 ms  143.281 ms
18  128.52.60.32 (128.52.60.32)  118.197 ms
    mitnet.core-1-ext.csail.mit.edu (18.0.162.142)  124.562 ms
    128.52.60.32 (128.52.60.32)  112.789 ms

❯ curl -k https://console-openshift-console.apps.smaug.na.operate-first.cloud
curl: (7) Failed to connect to console-openshift-console.apps.smaug.na.operate-first.cloud port 443: Connection refused

❯ curl -k http://console-openshift-console.apps.smaug.na.operate-first.cloud 
curl: (7) Failed to connect to console-openshift-console.apps.smaug.na.operate-first.cloud port 80: Connection refused
```

**Comment by larsks** [comment]
> curl: (7) Failed to connect to console-openshift-console.apps.smaug.na.operate-first.cloud port 443: Connection refused

I was seeing this earlier today as well, but as far as I could tell those packets weren't actually arriving at the machine that owns 128.52.60.32. It seems to be working now. If it fails at a convenient time on Monday I'm going to try to get someone to help with some layer 2 diagnostics on the switches.

**Comment by larsks** [comment]
Yay, I've finally spotted an actual problem w/r/t to our console access issues. I see the default ingress ip hosted on two nodes right now:

```
$ ansible -i hosts oct-03-29-compute,oct-03-10-compute -m shell -a 'ip addr | grep 128.52.60.32'
oct-03-29-compute | CHANGED | rc=0 >>
    inet 128.52.60.32/32 scope global noprefixroute enp4s0f0np0
oct-03-10-compute | CHANGED | rc=0 >>
    inet 128.52.60.32/32 scope global enp4s0f0np0
```

So there is definitively a problem with the cluster.

**Comment by larsks** [comment]
I've rebooted both systems that were hosting the ingress address. It's working reliably for me at the moment.

**Comment by durandom** [comment]
If this was actually the root cause, can we prevent this from happening again? Or alert on a situation like this `alert if ingress nodes have the same IP`

**Comment by larsks** [comment]
I worry that an alert for this *specific* situation wouldn't be all that useful. I think it would make more sense to alert on the console not being available. It would make sense to have an off-site monitor that just checks for the availability of public-facing services (i.e., api and console access for all our clusters, and other apps like argocd, etc).

**Comment by suppathak** [comment]
Is smaug cluster still down? I am unable to open this [page](https://console-openshift-console.apps.smaug.na.operate-first.cloud/) . I have been experiencing downtime from last Friday onwards.

**Comment by oindrillac** [comment]
Sesheta does not seem to be triggering `restest`s on this PR - https://github.com/aicoe-aiops/ocp-ci-analysis/pull/391
Do thoth services remain affected by this Smaug outage?

**Comment by HumairAK** [comment]
@oindrillac it's possible Sesheta/Prow issues are due to storage issues, these are being investigated today. Will keep you posted.

@suppathak thanks for letting us know, also noticed others are having console issues, we'll continue to look into this.

**Comment by larsks** [comment]
The object storage issue is being worked in https://access.redhat.com/support/cases/#/case/03095663
