### ISSUE TITLE
[INCIDENT] Authentication Down on Operate-First clusters infra, smaug, rick, balrog

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#435]
**Describe the bug**
Moc Infra has expired certificate. That also means Keycloak's certificate is expired and users can't log in to any of the Operate First clusters

**To Reproduce**
1. Go to https://console-openshift-console.apps.smaug.na.operate-first.cloud/
2. Click on "Login with -> operate-first"
3. See error

**Expected behaviour**
Valid cert

**Screenshots**
![image](https://user-images.githubusercontent.com/7453394/145025656-c3a86575-01a7-467a-86ea-74fe8eb6cb15.png)

![image](https://user-images.githubusercontent.com/7453394/145025700-cbaa9b46-fe56-4dfb-96a6-8c59b6e9c71e.png)

**Comment by HumairAK** [comment]
Outage is resolved by manually intervening and deploying cert-manager. But let's wait until this is merged before resolving the thread: https://github.com/operate-first/apps/pull/1416#pullrequestreview-826692614
