### ISSUE TITLE
Short URL and QR code for OpenShift Commons Gathering

### ISSUE THREAD

**Issue by quaid** [operate-first/sre#45]
My apologies for not having done this as an issue to start so @schwesig wouldn't have to duplicate effort.

This short URL is more specific and reusable, the hyphen is to keep in the common style:

op1.st/sig-sre

It should point to:

operate-first.cloud/sig-sre/

(I thought about having a stand-alone landing page but it's better to have the main page do the work for us.)

/assign @schwesig

**Comment by quaid** [comment]
QR code I generated that links to https://op1.st/sig-sre:

![op1 st--sig-sre](https://user-images.githubusercontent.com/112760/197665543-1f301580-b378-4d70-8d87-89860e7d3656.png)

**Comment by schwesig** [comment]
done
[op1.st/sig-sre](https://op1.st/sig-sre) --> 
[operate-first.cloud/sre](https://operate-first.cloud/sre)

![QR_https___op1 st_sig-sre](https://user-images.githubusercontent.com/89909507/197753915-ba0efbd5-0389-4410-b528-319efb605bc2.svg)
![QR_https___op1 st_sig-sre](https://user-images.githubusercontent.com/89909507/197753919-835c5970-f4c4-4a59-9720-cd9bf53bd659.png)
