### ISSUE TITLE
[Docs] Document the process for adding public facing Grafana dashboards

### ISSUE THREAD

**Issue by hemajv** [operate-first/SRE#5]
Once we have the dashboard publicly available (#18) we should document the process for getting it added to our repo.
This is also related to https://github.com/operate-first/apps/issues/92.

**Comment by HumairAK** [comment]
If ODH does not have a dashboard for JH, we should create one and document the procedure for adding it to our fork/repos and send these dashboards upstream.

**Comment by HumairAK** [comment]
First confirm with odh (likely via issue upstream) if there are plans to add such grafana dashboards and the eta. Based on this feedback, we should discuss here whether we need to proceed with adding our own and sending them upstream.

**Comment by hemajv** [comment]
> First confirm with odh (likely via issue upstream) if there are plans to add such grafana dashboards and the eta. Based on this feedback, we should discuss here whether we need to proceed with adding our own and sending them upstream.

Issue opened here: https://github.com/opendatahub-io/odh-manifests/issues/218

**Comment by HumairAK** [comment]
Looks like they are open to more dashboards and don't have any in the works, so I'd say we go ahead and add some dashboards for ourselves, then keep them general enough and send them upstream.
