### ISSUE TITLE
Create issue template for user complaints

### ISSUE THREAD

**Issue by hemajv** [operate-first/SRE#51]
Currently, we have issues being created for only Prometheus alerts. We need to also have an issue template for manually created issues such as capturing user complaints.

Related to #50

**Comment by drbwa** [comment]
@hemajv I just had the honor of creating my first issue/incident ticket: <https://github.com/operate-first/support/issues/83>. Maybe this incident can also serve as inspiration for what kind of information we would want to capture about these types of events?

**Comment by hemajv** [comment]
@drbwa I think it can definitely be a starting point for defining the incident templates, thank you for pointing it out! :+1:
