### ISSUE TITLE
Alert receiver for cluster monitoring 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#56]
Recently we were caught off guard with Kibana going down, we should see if this is something we can add to our monitoring and sync up with github alert receiver.

Edit by tumido: Original title was **Monitoring for Kibana (CLO)**. Repurposing this issue for more robust solution.

Edit checklist:
- [x] Create a namespace (https://github.com/operate-first/apps/pull/366)
- [x] Add a standalone alert receiver deployment (https://github.com/operate-first/apps/pull/367)
- [x] Create apps for the standalone deployment (https://github.com/operate-first/argocd-apps/pull/100)
- [x] Reconnect the opf-monitoring to this new standalone deployment (https://github.com/operate-first/apps/pull/368)
- [x] Cleanup deployment from opf-monitoring (https://github.com/operate-first/apps/pull/369)
- [x] Connect cluster monitoring on infra cluster to this receiver (https://github.com/operate-first/apps/pull/370)
- [ ] Use it for zero cluster as well (https://github.com/operate-first/apps/pull/389)

**Comment by tumido** [comment]
The cluster logging and other supported operators are monitored via the cluster monitoring and alerting. We just need to set up the receiver there so we can be alerted on all of these events.

https://docs.openshift.com/container-platform/4.6/monitoring/managing-alerts.html#applying-custom-alertmanager-configuration_managing-alerts

cc @hemajv @4n4nd

**Comment by tumido** [comment]
Hi @hemajv I'll take this one and implement it right away, ok? We'd like to have the infra cluster hooked up to this before we proceed with the migration/reinstall of CNV.

**Comment by hemajv** [comment]
@tumido of course, please go ahead 👍

**Comment by tumido** [comment]
Hey! Why are you reading your work notifications on PTO, @hemajv !? Go now and enjoy your time off! :smile: :stuck_out_tongue:
