### ISSUE TITLE
remove 'in progress' label when 'solved' label is applied

### ISSUE THREAD

**Issue by goern** [operate-first/SRE#61]
SSIA

**Comment by hemajv** [comment]
I think @tumido is fixing this in the PR: https://github.com/operate-first/apps/pull/367

**Comment by tumido** [comment]
well, I wouldn't call it a fix. :smile: it's rather disappearing of the issue.  :smile:

**Comment by hemajv** [comment]
haha right, so according to https://github.com/m-lab/alertmanager-github-receiver/issues/49#issuecomment-795700432, it seems like the labels were never really meant to be removed. Also, the github issue template is "static" and there is currently no option to configure this like for eg: providing an external issue template file to read from. So, I think for now your update seems to be the best option :smiley:
