### ISSUE TITLE
Look into adding/registering insights via cloud.redhat.com

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#67]

**Comment by tumido** [comment]
MOC cluster at OCM https://cloud.redhat.com/openshift/details/84eb607e-1679-44f8-8539-ff5b0179c79d

**Comment by tumido** [comment]
@larsks what can we do to have those clusters registered to c.r.c OCM? And is there a way for our RH folks to gain access to the c.r.c for this account? Do they have to be listed as part of the "customer" account or can we just request them to be added somehow?

**Comment by larsks** [comment]
@tumido  the cnv cluster was never registered with OCM to the best of my knowledge. I'll have to figure out what needs to happen (and whether that has entitlement or budget impacts of which we need to be aware).

**Comment by tumido** [comment]
To give a bit of context to this: we'd like to be able to consume recommendations and alerts from c.r.c. as well, hoping it would provide us enough visibility into what is going on with our clusters. This goes along with other efforts like hooking up the cluster monitoring to GH issues etc.

**Comment by larsks** [comment]
@tumido quick question, what is "c.r.c"? In the context of OpenShift that means to me "CodeReady Containers", which seems wrong in the context of this issue.

**Comment by tumido** [comment]
@larsks 
c.r.c. == cloud.redhat.com
CRC == CodeReady Containers

Because Red Hat is really good with acronyms. :smile:

**Comment by HumairAK** [comment]
Bump. Any updates on this?

**Comment by HumairAK** [comment]
@durandom
