### ISSUE TITLE
Aggregate avaibility of services alerting rules into one alerting rule

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#82]
Currently we set alerting rules that use the `up` method which, when prom goes down, results in all services reporting as also being down (even if these services are still up).  A suggestion proposed by @hemajv  is to aggregate all the `up` alerts into one alert called `overall_opf_status` and then alert on this metric only if/when prometheus goes down. The other `up` alerts can remain for basic availability.

**Comment by anishasthana** [comment]
We already do this via recording rules internally. It greatly simplified our long term uptime tracking as well. I'd recommend taking a look at https://gitlab.cee.redhat.com/data-hub/dh-monitoring/-/blob/master/prometheus/prometheus.yaml#L1510 for ideas :-)

**Comment by hemajv** [comment]
We will need to scrape the liveliness probe endpoints in order to create the recording rules that Anish pointed us to
