### ISSUE TITLE
Migrating ArgoCD to MOC-Infra

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#83]
[MOC-Infra](https://console-openshift-console.apps.moc-infra.massopen.cloud/k8s/cluster/projects) has been provisioned via ACM, and we'll migrating ~some (all?)~ management apps (i.e. ArgoCD) to this cluster as MOC-CNV is currently in an unstable state and is undergoing investigation/debuggin, see [here](https://console-openshift-console.apps.moc-infra.massopen.cloud/k8s/cluster/projects) for more info. This issue will serve as a central point for migration discussion. 

- [x] Deploy ArgoCD on moc-infra
- [x] Scale down ArgoCD on moc-cnv
- [x] Update Docs

**Comment by tumido** [comment]
If I understood it correctly, the MOC infra should be our target cluster for management (ACM + ArgoCD + Keycloak, etc.). our strategy should be to migrate the ArgoCD here and have it deployed here only.

**Comment by HumairAK** [comment]
Permissions added by @tumido [here](https://github.com/operate-first/apps/pull/275)

**Comment by HumairAK** [comment]
Scaled down moc-cnv argocd.

**Comment by HumairAK** [comment]
All argocd apps were moved to the new location.

**Comment by HumairAK** [comment]
Once docs are updated we can close this ticket.

**Comment by HumairAK** [comment]
This is issue has been resolved, closing.
