### ISSUE TITLE
Kibana in yellow state

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#98]
Initially reported by @drbwa

![image](https://user-images.githubusercontent.com/10904967/109659526-c267d580-7b35-11eb-938b-d52af8641ccd.png)

**Comment by HumairAK** [comment]
Restarting kibana pod

**Comment by HumairAK** [comment]
Issue seems to be with kibana indices: 

curl -XGET https://elasticsearch-openshift-logging.apps.cnv.massopen.cloud/_cat/indices/.kibana* 

```
green  open .kibana_-1648469826_dfroehliredhatcom      A8b6Vo9qQUCsdpfwLYn9Qw 2 0 1 0  3.9kb  3.9kb
green  open .kibana_145697694_fmurdacaredhatcom        jgSiCNxDQ-qSIRHsHWgg8Q 3 0 1 0  4.2kb  4.2kb
green  open .kibana_975435950_robbaronbuedu            3g5EjzkxSQuMUbEKD39Ovg 3 0 1 0  4.2kb  4.2kb
green  open .kibana_-1648469826_dfroehliredhatcom_2    yGaWFcgUShajOAPhaWaTuQ 1 1 0 0   523b   261b
green  open .kibana_-22725023_tcoufalredhatcom         wEtOMexARwOZomZ0oc4qKQ 2 0 2 0 25.2kb 25.2kb
green  open .kibana_-352715228_brunowassermanngmailcom 1DOxoSFLT3SxxiZMClOl0w 2 0 3 0 33.4kb 33.4kb
yellow open .kibana_1                                  uWzo2wy2T6CxECOgKcQzsg 1 1 0 0   522b   261b
green  open .kibana_-343928101_ronenschaffergmailcom   JZt3ST12Tr20YDvZVUcqNA 3 0 1 0  4.2kb  4.2kb
green  open .kibana_433326342_hukhanredhatcom          b-BHxb-_TLO4nMuAht-8fQ 2 0 3 0 33.9kb 33.9kb
green  open .kibana_1144518233_asanmukhredhatcom       dkA6eB0TR66Okcn2mtvZsw 2 0 3 0 33.4kb 33.4kb
green  open .kibana_964535869_coufaltomgmailcom        fhEbvEn9S2e279nOIziKDA 2 0 1 0  3.9kb  3.9kb
```

When I continue to curl this endpoint, I see that `.kibana_-1648469826_dfroehliredhatcom_2 ` index fluctuates between yellow/green: 

```
yellow open .kibana_-1648469826_dfroehliredhatcom_2    yGaWFcgUShajOAPhaWaTuQ 1 1 0 0   261b   261b
```

**Comment by HumairAK** [comment]
So looking at this issue thread [here](https://access.redhat.com/solutions/5332221), the possible suggestion is that: 

> as it's possible that kibana internal user migration is failing and thus a manual clean-up of these data may be required.

**Comment by HumairAK** [comment]
From kibana logs: 
> {"type":"log","@timestamp":"2021-03-02T14:06:54Z","tags":["warning","migrations"],"pid":121,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_-1648469826_dfroehliredhatcom_2 and restarting Kibana."}

As per the resolution advice in the link above, I'm going to delete this offending index.

**Comment by HumairAK** [comment]
Going to restart kibana pod to force new migration attempt

**Comment by HumairAK** [comment]
Now it is complaining about migration issues with another user: 

>{"type":"log","@timestamp":"2021-03-02T14:33:24Z","tags":["warning","migrations"],"pid":121,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_-22725023_tcoufalredhatcom_2 and restarting Kibana."}

I will try deleting this user's index as well, but I suspect it's going to complain about another one.

**Comment by HumairAK** [comment]
> {"type":"log","@timestamp":"2021-03-02T14:36:57Z","tags":["warning","migrations"],"pid":122,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_-343928101_ronenschaffergmailcom_2 and restarting Kibana."} 

:facepalm:

**Comment by HumairAK** [comment]
I deleted `.kibana_-343928101_ronenschaffergmailcom_2` now I'm seeing: 

![image](https://user-images.githubusercontent.com/10904967/109665269-fe059e00-7b3b-11eb-9dc1-78bd45aca2d4.png)


rebooting kibana to try again

**Comment by HumairAK** [comment]
Back to the same error above, going to delete these users one by one as it requests it and list the indices deleted all together, in hopes that will fix it. I could blanket delete all of them but I'd like to avoid that in the off chance it's only a subset of indices.

**Comment by HumairAK** [comment]
Okay so in the end it basically had me iterate through all .kibana_* user indices and delete all of them. This resulted in deleting all .kibana* indices except for `.kibana_1`. The general trend was: 

See error like: 

```
{"type":"log","@timestamp":"2021-03-02T15:12:45Z","tags":["warning","migrations"],"pid":121,"message":"Another Kibana instance appears to be migrating the index. Waiting for that migration to complete. If no other Kibana instance is attempting migrations, you can get past this message by deleting index .kibana_433326342_USER_2 and restarting Kibana."}
```

Search indices and find something like: 
```
.kibana_433326342_USER_2 
.kibana_433326342_USER
```
Deleting `.kibana_433326342_USER_2` just results in the same error again, deleting `.kibana_433326342_USER_2` and `.kibana_433326342_USER` results in kibana complaining about the next user, where you have to basically repeat the process. 

If we encounter this issue again, currently my suggestion is to try deleting the individual user's .kibana_* indices and if it complains about another user, then proceed to delete all .kibana_* indices.

**Comment by HumairAK** [comment]
kibana is complaining that it detects no data in ES (ES seems fine), going to just blanket delte .kibana_* indices and restart the pod.

**Comment by HumairAK** [comment]
```
Couldn't find any Elasticsearch data

You'll need to index some data into Elasticsearch before you can create an index pattern. Learn how or get started with some sample data sets.
```

Seems to be resulting due to: 

```
{"type":"log","@timestamp":"2021-03-02T16:06:18Z","tags":["error","elasticsearch","data"],"pid":121,"message":"Request error, retrying\nPOST https://elasticsearch.openshift-logging.svc.cluster.local:9200/*/_search?ignore_unavailable=true => socket hang up"}
```

**Comment by HumairAK** [comment]
We suspect network bottlneck at the ES level, we're going to increase the replica count and see if this mitigates it.

**Comment by HumairAK** [comment]
We're seeing kibana now read elasticsearch data, going to monitor further before confirming resolution.

**Comment by HumairAK** [comment]
Action item: monitor network traffic and load for ES

**Comment by HumairAK** [comment]
@drbwa -- Kibana should be up again, we had to wipe user indices based on reasons mentioned above (i.e. index migration issues). So if you had any index patterns / graphs setup those would be gone. Let us know if there are any further issues with Kibana! Resolving for now.

**Comment by drbwa** [comment]
@HumairAK Sorry to report that Kibana is in yellow state again, complaining about `Tenant indices migration failed`.

**Comment by HumairAK** [comment]
@drbwa thanks for the heads up, going to re-open this thread as I suspect the issue is the same.

**Comment by HumairAK** [comment]
It seems this time rebooting kibana had been enough to fix the migration issue.

**Comment by drbwa** [comment]
Thank you @HumairAK ! I will take Kibana for a spin. Great to be able to see what the impact of that might be using the new dashboards :-)

**Comment by HumairAK** [comment]
Sounds good @drbwa, please continues to let us know here if there are more issues!

I'll keep this issue open for a bit in case it goes down again, in the meantime I'll dig through the logs to see if there's anything amiss.
